### ISSUE TITLE
net-ssh does not handle non-multiplexed ssh connections

### ISSUE THREAD

**Issue by jakerobinson** [net-ssh/net-ssh#121]
When an opensshd server is set to `MaxSessions 1`, disabling multiplexing, every other `exec!()`  command fails with `open failed(1)`

```
/Users/jrobinson/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/connection/channel.rb:524:in `do_open_failed'
/Users/jrobinson/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/connection/session.rb:545:in `channel_open_failure'
/Users/jrobinson/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/connection/session.rb:459:in `dispatch_incoming_packets'
/Users/jrobinson/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/connection/session.rb:216:in `preprocess'
/Users/jrobinson/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/connection/session.rb:200:in `process'
/Users/jrobinson/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/connection/session.rb:164:in `block in loop'
/Users/jrobinson/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/connection/session.rb:164:in `loop'
/Users/jrobinson/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/connection/session.rb:164:in `loop'
/Users/jrobinson/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/connection/channel.rb:269:in `wait'
/Users/jrobinson/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/connection/session.rb:358:in `exec!'
```

**Comment by mfazekas** [comment]
I might misunderstood this issue but you should be able to open different connection and do just one exec per connection

**Comment by davidpowerwpe** [comment]
I also ran in to this issue when trying to use Serverspec to talk to a server with MaxSession set to 1.

**Comment by davidpowerwpe** [comment]
@jakerobinson did you ever resolve / get around this issue?

**Comment by jakerobinson** [comment]
@davidpowerwpe Sadly I never had a chance to fix it in net-ssh. I ended up defaulting MaxSessions to 10 by deleting the line. We decided the very small security precaution was not worth breaking most of our automation.

**Comment by mfazekas** [comment]
Guys if you can demonstrate the issue in a small net-ssh script to reproduce the issue that would make stuff much more straightforward.

**Comment by jakerobinson** [comment]
Thanks @mfazekas, I was wrong not to include that when I first submitted this issue.

Setup: Add the line `MaxSessions 1` to the remote machine's `/etc/ssh/sshd_config` and restart sshd.

Run the following with the correct host and credentials:
https://gist.github.com/jakerobinson/827e4fec5b9e5ff45b68997006f1aceb

Expected result (achieved when `MaxSessions 10`):
```
2.0.0-p576 :010 >   Net::SSH.start('10.144.32.127', 'root', :password => "zombie") do |ssh|
2.0.0-p576 :011 >       for i in 0..9
2.0.0-p576 :012?>         output = ssh.exec!("hostname")
2.0.0-p576 :013?>         puts output
2.0.0-p576 :014?>       end
2.0.0-p576 :015?>   end
flower
flower
flower
flower
flower
flower
flower
flower
flower
flower
 => 0..9 
```

Actual result (MaxSessions 1):
```
Net::SSH::ChannelOpenFailed: open failed (1)
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh/connection/channel.rb:544:in `do_open_failed'
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:560:in `channel_open_failure'
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:474:in `dispatch_incoming_packets'
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:222:in `preprocess'
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:206:in `process'
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:170:in `loop'
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:170:in `loop'
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh/connection/channel.rb:269:in `wait'
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:365:in `exec!'
	from (irb):15:in `block (2 levels) in irb_binding'
	from (irb):14:in `each'
	from (irb):14:in `block in irb_binding'
	from /Users/jrobinson/.rvm/gems/ruby-2.0.0-p576/gems/net-ssh-2.9.4/lib/net/ssh.rb:215:in `start'
	from (irb):13
	from /Users/jrobinson/.rvm/rubies/ruby-2.0.0-p576/bin/irb:12:in `<main>'
```

**Comment by mfazekas** [comment]
@jakerobinson 

This doesn't works for me

```ruby
Net::SSH.start('1.2.3.4', 'root', :password => "foobar") do |ssh|
  for i in 0..9
   output = ssh.exec!("hostname")
   puts output
 end
end
```

But this does

```ruby
Net::SSH.start('1.2.3.4', 'root', :password => "foobar") do |ssh|
  for i in 0..9
   output = ssh.exec!("hostname")
   puts output
   ssh.process # !!!
 end
end
```
