### ISSUE TITLE
IO::EAGAINWaitReadable: Resource temporarily unavailable on jruby 1.7.4

### ISSUE THREAD

**Issue by nchainani** [net-ssh/net-ssh#122]
Here is the environment
jruby 1.7.4

gem list
*** LOCAL GEMS ***

bouncy-castle-java (1.5.0146.1)
bundler (1.2.4)
jruby-launcher (1.0.15 java)
jruby-openssl (0.8.2)
net-ssh (2.7.0)
rake (10.0.3)
rubygems-bundler (1.1.0)
rvm (1.11.3.6)

When I try Net::SSH.start("xxx.xxxx.xxx", 'username') {|ssh| } i get this error
IO::EAGAINWaitReadable: Resource temporarily unavailable - errno backtraces disabled; run with -Xerrno.backtrace=true to enable

This might not be a net-ssh error, I am not sure.

**Comment by ebenoist** [comment]
+1 seeing the same thing.

**Comment by mfazekas** [comment]
It would help to have a detailed(or automated) description to reproduce the issue.

**Comment by deepredsky** [comment]
I have similar problem as well
using 3.0.1
on ruby 2.2.* versions

here is a sample code snippet that triggers this error for me

```ruby
require 'net/ssh'
require 'net/ssh/proxy/command'

Net::SSH.start('abc.domain.com', 'deployer', proxy: Net::SSH::Proxy::Command.new('ssh deployer@gateway.com -W %h:%p')) do |ssh|
  # capture all stderr and stdout output from a remote process
  output = ssh.exec!("hostname")
  puts output
end
```

and the trace

```
/Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/proxy/command.rb:82:in `write_nonblock': Resource temporarily unavailable - write would block (IO::EAGAINWaitWritable)
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/proxy/command.rb:82:in `send'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/buffered_io.rb:99:in `send_pending'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/buffered_io.rb:115:in `wait_for_pending_sends'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/packet_stream.rb:118:in `send_packet'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:233:in `send_message'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/algorithms.rb:190:in `send_kexinit'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/algorithms.rb:146:in `accept_kexinit'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:202:in `block in poll_message'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:180:in `loop'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:180:in `poll_message'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:217:in `block in wait'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:215:in `loop'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:215:in `wait'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh/transport/session.rb:87:in `initialize'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh.rb:222:in `new'
from /Users/anon/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.1/lib/net/ssh.rb:222:in `start'
from tmp/ssh.rb:4:in `<main>'
```

**Comment by ahmeij** [comment]
I have the same issues on OSX ElCapitan. Whatever I tried it did not work, not via .ssh/config proxies, not via manually building a ProxyCommand object.

I finally hacked around the issue with the following patch:


    net-ssh-3.0.1/lib/net/ssh/proxy/command.rb
    82c82,88
           write_nonblock(data)
    ---
           tries = 0
           begin
             write_nonblock(data)
           rescue IO::EAGAINWaitWritable
             sleep 0.01
             retry unless tries > 1
           end

**Comment by mfazekas** [comment]
@ahmeij Thanks. I think the current code of replacing https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/proxy/command.rb#L81 is definitely broken. I think we're using send in blocking mode, so here we want to send at last 1 byte, but we don't want to wait to send all the bytes.
So maybe such approach would be closer in semantics:
```ruby
begin
  result = io.write_nonblock(data)
rescue IO::WaitWritable, Errno::EINTR
  IO.select(nil, [io])
  retry
end
result
```

**Comment by deepredsky** [comment]
I tried to rescue and retry as well. However, it still does not work for me after 3-4 retries. A computer restart always works for some reason. FYI I am also on El Capitan

**Comment by TiagoCardoso1983** [comment]
Maybe [related](https://github.com/celluloid/celluloid-io/issues/156) ?

**Comment by mfazekas** [comment]
I was able to reproduce the issue on linux. (I've had to simulate spurious wakeups in select - it's possible that it happens more in your env)
```
 208kB 0:00:02 [88.1kB/s] [      <=>                                                                                                       ]
 = 2.52 s
  1) Error:
test_smoke3(TestProxy):
Errno::EAGAIN: Resource temporarily unavailable - write would block
    /net-ssh/lib/net/ssh/proxy/command.rb:83:in `write_nonblock'
    /net-ssh/lib/net/ssh/proxy/command.rb:83:in `send'
    /net-ssh/lib/net/ssh/buffered_io.rb:99:in `send_pending'
    /net-ssh/lib/net/ssh/connection/session.rb:245:in `block in postprocess'
    /net-ssh/lib/net/ssh/connection/session.rb:244:in `each'
    /net-ssh/lib/net/ssh/connection/session.rb:244:in `postprocess'
    /net-ssh/lib/net/ssh/connection/session.rb:212:in `process'
    /net-ssh/lib/net/ssh/connection/session.rb:170:in `block in loop'
    /net-ssh/lib/net/ssh/connection/session.rb:170:in `loop'
    /net-ssh/lib/net/ssh/connection/session.rb:170:in `loop'
    /net-ssh/lib/net/ssh/connection/channel.rb:269:in `wait'
    /net-ssh/lib/net/ssh/connection/session.rb:365:in `exec!'
```
