### ISSUE TITLE
Errno::EBADF: Bad file descriptor - known_hosts

### ISSUE THREAD

**Issue by mzahir** [net-ssh/net-ssh#128]
Hi,

I occasionally get the exception `Errno::EBADF: Bad file descriptor - /home/user/.ssh/known_hosts` when attempting to access the server (via the Rye gem).

````ruby
net/ssh/known_hosts.rb:107:in `each_line`
net/ssh/known_hosts.rb:107:in `block in keys_for`
lib/net/ssh/known_hosts.rb:105:in `open`
lib/net/ssh/known_hosts.rb:105:in `keys_for`
lib/net/ssh/known_hosts.rb:35:in `block in search_in`
lib/net/ssh/known_hosts.rb:35:in `map`
lib/net/ssh/known_hosts.rb:35:in `search_in`
lib/net/ssh/known_hosts.rb:29:in `search_for`
lib/net/ssh/transport/algorithms.rb:237:in `prepare_preferred_algorithms!`
lib/net/ssh/transport/algorithms.rb:120:in `initialize`
lib/net/ssh/transport/session.rb:80:in `new`
lib/net/ssh/transport/session.rb:80:in `initialize`
lib/net/ssh.rb:200:in `new`
lib/net/ssh.rb:200:in `start`
lib/rye/box.rb:669:in `connect`
````
Is this a synchronization issue? It seems like the session attempts to open a file that has already been closed.

Any help would be great, thanks.

**Comment by mfazekas** [comment]
net-ssh is not thread safe in many ways.
