### ISSUE TITLE
can't exec anything when connected to Cisco IOS XRv

### ISSUE THREAD

**Issue by Nowaker** [net-ssh/net-ssh#156]
net-ssh is able to connect but fails when I try to exec anything. When running the same command (`terminal length 0`) from my terminal it just works. I don't experience any problems when connecting to Linux SSH servers.

Here's a full log (`:verbose => :debug`) along with a stacktrace from Ruby 1.8:

```
establishing connection to 192.168.0.55:22
connection established
negotiating protocol version
remote is `SSH-2.0-Cisco-2.0'
local is `SSH-2.0-Ruby/Net::SSH_2.8.0 x86_64-linux'
read 240 bytes
received packet nr 0 type 20 len 236
got KEXINIT from server
sending KEXINIT
queueing packet nr 0 type 20 len 1620
sent 1624 bytes
negotiating algorithms
negotiated:
* kex: diffie-hellman-group1-sha1
* host_key: ssh-dss
* encryption_server: aes128-cbc
* encryption_client: aes128-cbc
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
exchanging keys
queueing packet nr 1 type 30 len 140
sent 144 bytes
read 640 bytes
received packet nr 1 type 31 len 636
queueing packet nr 2 type 21 len 20
sent 24 bytes
read 16 bytes
received packet nr 2 type 21 len 12
beginning authentication of `root'
queueing packet nr 3 type 5 len 28
sent 52 bytes
read 52 bytes
received packet nr 3 type 6 len 28
trying none
queueing packet nr 4 type 50 len 44
sent 68 bytes
read 1124 bytes
received packet nr 4 type 53 len 1100



IMPORTANT:  READ CAREFULLY
Welcome to the Demo Version of Cisco IOS XRv (the "Software").
The Software is subject to and governed by the terms and conditions
of the End User License Agreement and the Supplemental End User
License Agreement accompanying the product, made available at the
time of your order, or posted on the Cisco website at
www.cisco.com/go/terms (collectively, the "Agreement").
As set forth more fully in the Agreement, use of the Software is
strictly limited to internal use in a non-production environment
solely for demonstration and evaluation purposes.  Downloading,
installing, or using the Software constitutes acceptance of the
Agreement, and you are binding yourself and the business entity
that you represent to the Agreement.  If you do not agree to all
of the terms of the Agreement, then Cisco is unwilling to license
the Software to you and (a) you may not download, install or use the
Software, and (b) you may return the Software as more fully set forth
in the Agreement.


Please login with any configured user/password, or cisco/cisco



read 52 bytes
received packet nr 5 type 51 len 28
allowed methods: password
none failed
trying password
queueing packet nr 5 type 50 len 60
sent 84 bytes
read 36 bytes
received packet nr 6 type 52 len 12
password succeeded
queueing packet nr 6 type 90 len 44
closing remaining channels (1 open)
sent 68 bytes
read 52 bytes
received packet nr 7 type 91 len 28
channel_open_confirmation: 0 1 131072 32768
sending channel request "exec"
queueing packet nr 7 type 98 len 44
sent 68 bytes
read 36 bytes
received packet nr 8 type 99 len 12
channel_success: 0


Sat Mar 29 21:24:12.861 UTC
read 84 bytes
received packet nr 9 type 94 len 60
channel_data: 0 33b
read 68 bytes
received packet nr 10 type 98 len 44
channel_request: 0 exit-status false
read 72 bytes
read 0 bytes



Net::SSH::Disconnect: connection closed by remote host
/home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/transport/packet_stream.rb:87:in `next_packet'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/transport/session.rb:178:in `poll_message'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/transport/session.rb:173:in `loop'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/transport/session.rb:173:in `poll_message'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:460:in `dispatch_incoming_packets'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:221:in `preprocess'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:205:in `process'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `loop'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `loop_forever'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `loop'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:118:in `close'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/net-ssh-2.8.0/lib/net/ssh.rb:210:in `start'
    lib/cisco/ssh_configurator.rb:9:in `configure'
    test/unit/cisco/ssh_configurator_test.rb:10:in `test_should_Ruby_and_Excel_generated_configs_equal'
```

**Comment by dimult** [comment]
@bryanculver, how do you do that?
I mean where u was find needed code, what kind of file of Net::SSH?

**Comment by mfazekas** [comment]
3.0.2 should be much better as it no longer advertises unsupported algorithms so KEXINIT is smaller. Please reopen if persist with 3.0.2
