### ISSUE TITLE
Streaming large files (>4GB) fails with hang

### ISSUE THREAD

**Issue by hhercules** [net-ssh/net-ssh#233]
I just ran into this too, just when I thought I had solution I ran into this limit. What I am doing is a little different than net-sftp, I am using net-ssh connection sessions. I am passing command to run remotely and output data to console. Something like "cd /directory && tar cz directory2", it stops basically same place reported above. 
```
$ ls -ltrh ../local/
-rw-rw-r-- 1 user user 4.0G Mar 17 09:54 file.tgz

$ ls -ltr ../local/
-rw-rw-r-- 1 user user 4294967296 Mar 17 09:54 file.tgz
```
When I CTRL-C it after it has hung this is what it shows:
```
^C/home/user/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `select': Interrupt
        from /home/user/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `io_select'
        from /home/user/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:209:in `process'
        from /home/user/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
        from /home/user/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from /home/user/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from ./backup2.rb:53:in `block in <main>'
        from /home/user/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh.rb:210:in `start'
        from ./backup2.rb:51:in `<main>'
```

This is def I am using:
```
def do_tgz( session, cmd )
  session.open_channel do |channel|
    channel.on_data do |ch, data|
      print "#{data}"
    end
    channel.exec "#{cmd}"
  end
end
```
This is similar to https://github.com/net-ssh/net-sftp/issues/27.

**Comment by mfazekas** [comment]
I could not repro using the followin script:
```ruby
$:.push('./lib')
require 'net/ssh'
puts Net::SSH::Version::CURRENT
ssh = Net::SSH.start("localhost", ENV["USER"])   
bytes = 0
mbytes = 0
channel = ssh.open_channel do |channel|
  channel.on_data do |ch, data|
    bytes += data.length 
    newmbytes = bytes / (1024 * 1024)
    if newmbytes != mbytes
      puts "Bytes: #{mbytes} MB"
      puts "Bytes: #{bytes} bytes"
      mbytes = newmbytes
    end
  end
  channel.exec "cat /dev/zero"
end                      
channel.wait
ssh.close
```
I get to over 44 GB:
Bytes: 44798 MB
Bytes: 46975156224 bytes
Bytes: 44799 MB
Bytes: 46976204800 bytes

**Comment by mfazekas** [comment]
tried on 64 bit vagrant too. well be reopened once we have more information
