### ISSUE TITLE
Session#process.open doesn't work as expected

### ISSUE THREAD

**Issue by rickhull** [net-ssh/net-ssh#237]
per http://net-ssh.github.io/ssh/v1/chapter-4.html

```
Net::SSH.start('127.0.0.1', ENV['USER']) { |session|
  session.process.open('env') { |process|
    process.on_stdout { |p, data|
      $stdout.puts data
    }
  }
}
```

This just blocks forever.  I sent SIGINT to get a stacktrace:

```
^C/home/rwh/.gem/ruby/2.2.1/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `select': Interrupt
	from /home/rwh/.gem/ruby/2.2.1/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `io_select'
	from /home/rwh/.gem/ruby/2.2.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:209:in `process'
```

**Comment by rickhull** [comment]
Well, as best I can tell, this feature hasn't been supported in 7 or 8 years.  Session#process in the current code doesn't appear to do anything like what the documentation shows (the link I posted).  Does the `v1` in the URL refer to version 1.x of this gem?  You might consider putting a huge deprecation warning on those docs if so.

**Comment by rickhull** [comment]
Confirmed these docs are 8 years old.
