### ISSUE TITLE
Release 2.10.0 breaks test-kitchen

### ISSUE THREAD

**Issue by i11** [net-ssh/net-ssh#260]
It seems that 2.10.0 release breaks something in test-kitchen. Everything works fine with 2.9.2.

I either get a timeout exception

```
E, [2015-08-03T11:14:25.041195 #1883] ERROR -- Kitchen: ------Exception-------
E, [2015-08-03T11:14:25.041237 #1883] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2015-08-03T11:14:25.041264 #1883] ERROR -- Kitchen: Message: Failed to complete #create action: [Connection timed out - connect(2) for MYIPADDRESS:22]
E, [2015-08-03T11:14:25.041298 #1883] ERROR -- Kitchen: ---Nested Exception---
E, [2015-08-03T11:14:25.041322 #1883] ERROR -- Kitchen: Class: Errno::ETIMEDOUT
E, [2015-08-03T11:14:25.041351 #1883] ERROR -- Kitchen: Message: Connection timed out - connect(2) for MYIPADDRESS:22
E, [2015-08-03T11:14:25.041376 #1883] ERROR -- Kitchen: ------Backtrace-------
E, [2015-08-03T11:14:25.041399 #1883] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/socket.rb:60:in `connect_nonblock'
E, [2015-08-03T11:14:25.041424 #1883] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/socket.rb:60:in `rescue in connect_internal'
E, [2015-08-03T11:14:25.041447 #1883] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/socket.rb:53:in `connect_internal'
E, [2015-08-03T11:14:25.041471 #1883] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/socket.rb:140:in `connect'
E, [2015-08-03T11:14:25.041495 #1883] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/socket.rb:338:in `block in tcp'
E, [2015-08-03T11:14:25.041523 #1883] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/socket.rb:232:in `each'
E, [2015-08-03T11:14:25.041547 #1883] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/socket.rb:232:in `foreach'
E, [2015-08-03T11:14:25.041571 #1883] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/socket.rb:328:in `tcp'
E, [2015-08-03T11:14:25.041623 #1883] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/session.rb:70:in `initialize'
E, [2015-08-03T11:14:25.041649 #1883] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh.rb:221:in `new'
E, [2015-08-03T11:14:25.041673 #1883] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh.rb:221:in `start'
```

or  something about compression_client algorithm

```
E, [2015-08-03T11:09:56.484930 #1389] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2015-08-03T11:09:56.484955 #1389] ERROR -- Kitchen: Message: Failed to complete #create action: [could not settle on compression_client algorithm]
E, [2015-08-03T11:09:56.484979 #1389] ERROR -- Kitchen: ---Nested Exception---
E, [2015-08-03T11:09:56.485002 #1389] ERROR -- Kitchen: Class: Net::SSH::Exception
E, [2015-08-03T11:09:56.485030 #1389] ERROR -- Kitchen: Message: could not settle on compression_client algorithm
E, [2015-08-03T11:09:56.485054 #1389] ERROR -- Kitchen: ------Backtrace-------
E, [2015-08-03T11:09:56.485099 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/algorithms.rb:328:in `negotiate'
E, [2015-08-03T11:09:56.485126 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/algorithms.rb:308:in `negotiate_algorithms'
E, [2015-08-03T11:09:56.485161 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/algorithms.rb:199:in `proceed!'
E, [2015-08-03T11:09:56.485187 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/algorithms.rb:191:in `send_kexinit'
E, [2015-08-03T11:09:56.485211 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/algorithms.rb:146:in `accept_kexinit'
E, [2015-08-03T11:09:56.485238 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/session.rb:200:in `block in poll_message'
E, [2015-08-03T11:09:56.485263 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/session.rb:178:in `loop'
E, [2015-08-03T11:09:56.485287 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/session.rb:178:in `poll_message'
E, [2015-08-03T11:09:56.485310 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/session.rb:215:in `block in wait'
E, [2015-08-03T11:09:56.485334 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/session.rb:213:in `loop'
E, [2015-08-03T11:09:56.485357 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/session.rb:213:in `wait'
E, [2015-08-03T11:09:56.485381 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh/transport/session.rb:87:in `initialize'
E, [2015-08-03T11:09:56.485404 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh.rb:221:in `new'
E, [2015-08-03T11:09:56.485428 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/net-ssh-2.10.0/lib/net/ssh.rb:221:in `start'
E, [2015-08-03T11:09:56.485451 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/transport/ssh.rb:203:in `establish_connection'
E, [2015-08-03T11:09:56.485474 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/transport/ssh.rb:270:in `session'
E, [2015-08-03T11:09:56.485518 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/transport/ssh.rb:142:in `wait_until_ready'
E, [2015-08-03T11:09:56.485542 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/kitchen-ec2-0.10.0/lib/kitchen/driver/ec2.rb:214:in `create'
E, [2015-08-03T11:09:56.485565 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:424:in `public_send'
E, [2015-08-03T11:09:56.485588 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:424:in `block in perform_action'
E, [2015-08-03T11:09:56.485612 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `call'
E, [2015-08-03T11:09:56.485635 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2015-08-03T11:09:56.485658 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-08-03T11:09:56.485681 #1389] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-08-03T11:09:56.485705 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:452:in `action'
E, [2015-08-03T11:09:56.485734 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:424:in `perform_action'
E, [2015-08-03T11:09:56.485758 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:352:in `create_action'
E, [2015-08-03T11:09:56.485782 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-08-03T11:09:56.485805 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `each'
E, [2015-08-03T11:09:56.485829 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-08-03T11:09:56.485853 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:160:in `verify'
E, [2015-08-03T11:09:56.485892 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:189:in `block in test'
E, [2015-08-03T11:09:56.485916 #1389] ERROR -- Kitchen: /opt/rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-08-03T11:09:56.485944 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:185:in `test'
E, [2015-08-03T11:09:56.485968 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/command.rb:176:in `public_send'
E, [2015-08-03T11:09:56.485992 #1389] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-08-03T11:09:56.486015 #1389] ERROR -- Kitchen: ----------------------
```

**Comment by mfazekas** [comment]
@i11 thanks for the report. Is there an easy way for me to reproduce the issue?

Can you also try following versions:
https://rubygems.org/gems/net-ssh/versions/2.9.2
https://rubygems.org/gems/net-ssh/versions/2.9.3.beta1
https://rubygems.org/gems/net-ssh/versions/2.10.0.beta1
https://rubygems.org/gems/net-ssh/versions/2.10.0.beta2

**Comment by nbibler** [comment]
The 2.10.0 release also seems to be breaking Capistrano 2.x (2.15.5 and 2.15.6, certainly) deployments:

```
ArgumentError: wrong number of arguments (5 for 4)
```

**Comment by mfazekas** [comment]
@nbibler can you show the full stacktrace and the ruby version used?

**Comment by nbibler** [comment]
Trying to capture something for you ... Capistrano isn't the easiest thing to get exceptions out of.. ;)

**Comment by gesbo** [comment]
Also finding that 2.10.0 breaks test-kitchen when running against a Windows VM. 2.9.2 works completely fine and we are working around the issue by pinning to the older version using a Gemfile in our serverspec folder (as per https://github.com/test-kitchen/busser-serverspec).

Stacktrace snippet which may help:

    -----> serverspec installed (version 2.20.0)
       C:/opscode/chef/embedded/bin/ruby.exe -    IC:/Users/vagrant/AppData/Local/Temp/verifier/suites/serverspec -I'C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/rspec-support-3.3.0/lib';'C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/rspec-core-3.3.2/lib' 'C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/rspec-core-3.3.2/exe/rspec' --pattern 'C:/Users/vagrant/AppData/Local/Temp/verifier/suites/serverspec/**/*_spec.rb' --color --format documentation --default-path C:/Users/vagrant/AppData/Local/Temp/verifier/suites/serverspec
    $$$$$$ C:/opscode/chef/embedded/lib/ruby/1.9.1/dl/cparser.rb:104:in `parse_ctype': unknown type: uintptr_t (DL::DLError)
    $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/1.9.1/dl/cparser.rb:33:in `block in parse_struct_signature'
    $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/1.9.1/dl/cparser.rb:9:in `each'
    $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/1.9.1/dl/cparser.rb:9:in `parse_struct_signature'
    $$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/1.9.1/dl/import.rb:183:in `struct'
    $$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/net-ssh-2.10.0/lib/net/ssh/authentication/pageant.rb:157:in `<module:Win>'

I'll see if I can fashion a repeatable case for you.

**Comment by carlhoerberg** [comment]
Allan, looks like you're using Ruby 1.9, which isn't supported.

**Comment by gesbo** [comment]
@carlhoerberg yes, thanks for pointing that out. It looks as though we have a bigger problem we need to solve first...

**Comment by mfazekas** [comment]
Yanked 2.10.0 and released 2.10.1.rc1 with 2.0+ version requirement

https://rubygems.org/gems/net-ssh/versions/2.10.1.rc1

**Comment by nbibler** [comment]
:+1: Adding a Ruby 2.x requirement is definitely a good thing. I missed that Ruby 1.9 was dropped until after my initial post here.

**Comment by kbarber** [comment]
@mfazekas why did you drop Ruby support in a Y revision, not an X release? Feels like such a change would warrant a 3.x.

**Comment by mfazekas** [comment]
@kbarber 1.9.3 was EOL in February so it sounded like a safe decision to drop support for that. We can certainly name this release as 3.0.x or we can even try to support 1.9.3. It just doesn't sounded wise to spend any time on a ruby release no longer supported.

**Comment by tyler-ball** [comment]
We have fixed the 2.10 issues that popped up in test-kitchen, so I think the title of this bug is no longer correct.  Seems like this can be closed!

**Comment by mfazekas** [comment]
@tyler-ball the first report by @i11 - https://github.com/net-ssh/net-ssh/issues/260#issue-98723033 looks like on ruby 2.1.0 (non 1.9.3).  Can i get help reproducing that?

**Comment by i11** [comment]
@mfazekas yeah, I'm not sure if there is an easy way to reproduce it. My setup involves test kitchen ec2 driver used to run 20ish suites (=VMs) with concurrency of 10. There are quite a few moving parts...

I'll give it a try to the version you've mentioned and come back with the results later today. Let me know how I can be more helpful.

**Comment by i11** [comment]
Checked out https://github.com/test-kitchen/test-kitchen/releases/tag/v1.4.2 and as @tyler-ball mentioned the issue has been resolved. It wasn't just ruby 1.9, but other fixes like catching renamed timeout exception and setting the default compression. Even though net-ssh version range is set to prior 2.10 it actually works fine with 2.10.1.rc1.

To sum up there was nothing wrong with 2.10.0, just the lack of pinning in test kitchen. Sorry for blaming you guys...

This issue can be closed.
