### ISSUE TITLE
Ambiguous errors if no passphrase is specified for encrypted keys in key_data

### ISSUE THREAD

**Issue by Temikus** [net-ssh/net-ssh#290]
OpenSSL produces argument errors when decoding ssh keys from `:key_data` with incorrect passphrase:
```
>OpenSSL::PKey.read(data, 'invalid')
ArgumentError: Could not parse PKey: no start line
from (pry):4:in `read'
```
This, coupled with ssh-key passphrase requests in key_manager getting initialised first with `ask_passphrase` set to `false`:
```
user_identities = load_identities(prepared_identities, false, true)
```
, causes an exception to be raised immediately in the following rescue block in key_factory:
```
            rescue OpenSSL::PKey::RSAError, OpenSSL::PKey::DSAError, OpenSSL::PKey::ECError => e
              if ignore_decryption_errors
                identity
              else
                process_identity_loading_error(identity, e)
                nil
              end
            rescue ArgumentError => e
              process_identity_loading_error(identity, e)
              nil
            rescue Exception => e
              process_identity_loading_error(identity, e)
              nil
            end
``` 
, with an ambiguous traceback following:
```
/Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh/key_factory.rb:78:in `read': Could not parse PKey: no start line (ArgumentError)
	from /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh/key_factory.rb:78:in `load_data_private_key'
	from /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh/authentication/key_manager.rb:231:in `block in load_identities'
	from /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh/authentication/key_manager.rb:219:in `map'
	from /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh/authentication/key_manager.rb:219:in `load_identities'
	from /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh/authentication/key_manager.rb:102:in `each_identity'
	from /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
	from /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh/authentication/session.rb:79:in `block in authenticate'
	from /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh/authentication/session.rb:66:in `each'
	from /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh/authentication/session.rb:66:in `authenticate'
	from /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/net-ssh-3.0.1/lib/net/ssh.rb:226:in `start'
	from ./net_ssh_key.rb:12:in `<main>'
``` 

REPRODUCTION:
```
require 'net/ssh'


private_key = File.read("#{ENV['HOME']}/.ssh/id_rsa")

options = {}
options[:keys] = []
options[:key_data] = [private_key]

key_manager = Net::SSH::Authentication::KeyManager.new(nil, options)

Net::SSH.start("localhost", ENV['USER'], options) do |ssh|
  ssh.exec! 'whoami'
end
```
Tested on:
MacOSX 10.11.1
OpenSSL 1.0.2d 9 Jul 2015
Ruby 2.1.7
Ruby 2.2.3

**Comment by Temikus** [comment]
Ruby stdlib issue reported as well:
https://bugs.ruby-lang.org/issues/11774

**Comment by mfazekas** [comment]
:+1:  thanks for the PR!
