### ISSUE TITLE
KnownHosts caching?

### ISSUE THREAD

**Issue by byroot** [net-ssh/net-ssh#307]
Hi, I'm working on Capistrano's performance (see https://github.com/capistrano/sshkit/issues/326 for more context), and it appear that `Net::SSH::KnownHosts#keys_for` is a big hot spot during connection establishment.

The profiled code:
```
require 'stackprof'
task :profile do
  StackProf.run(mode: :wall, out: 'tmp/stackprof-cap-idle-cold.dump') do
    on servers do # About ~180 hosts
      execute :echo, 'ping > /dev/null'
    end
  end
end
```

```
==================================
  Mode: wall(1000)
  Samples: 4981 (5.73% miss rate)
  GC: 394 (7.91%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
      1880  (37.7%)        1874  (37.6%)     SSHKit::Runner::Parallel#execute
       476   (9.6%)         476   (9.6%)     block (3 levels) in Net::SSH::KnownHosts#keys_for
       859  (17.2%)         309   (6.2%)     block (2 levels) in Net::SSH::KnownHosts#keys_for
       276   (5.5%)         276   (5.5%)     Net::SSH::Compat.io_select
       183   (3.7%)         106   (2.1%)     OpenSSL::PKey::DH#valid?
       144   (2.9%)         102   (2.0%)     Net::SSH::Transport::Kex::DiffieHellmanGroup1SHA1#send_kexinit
        77   (1.5%)          77   (1.5%)     block in OpenSSL::PKey::DH#valid?
        63   (1.3%)          63   (1.3%)     block (2 levels) in Net::SSH::Transport::ServerVersion#negotiate!
       215   (4.3%)          53   (1.1%)     Net::SSH::Transport::PacketStream#poll_next_packet
        78   (1.6%)          52   (1.0%)     block in Net::SSH::Config.load
        50   (1.0%)          50   (1.0%)     Net::SSH::KnownHosts#known_host_hash?
        56   (1.1%)          47   (0.9%)     Net::SSH::Buffer#read
        46   (0.9%)          46   (0.9%)     block (2 levels) in Net::SSH::Connection::Channel#forward_local_env
       122   (2.4%)          44   (0.9%)     Net::SSH::Config.load
       934  (18.8%)          42   (0.8%)     Net::SSH::KnownHosts#keys_for
        70   (1.4%)          34   (0.7%)     Net::SSH::BufferedIo#fill
       892  (17.9%)          33   (0.7%)     block in Net::SSH::KnownHosts#keys_for
        31   (0.6%)          31   (0.6%)     Net::SSH::Buffer#write_long
        29   (0.6%)          29   (0.6%)     Logger#debug?
        28   (0.6%)          28   (0.6%)     Net::SSH::Buffer#initialize
        56   (1.1%)          26   (0.5%)     Net::SSH::Buffer#read_long
        26   (0.5%)          26   (0.5%)     Net::SSH::BufferedIo#input
        39   (0.8%)          25   (0.5%)     Net::SSH::BufferedIo#send_pending
        27   (0.5%)          24   (0.5%)     Net::SSH::Transport::State#update_next_iv
      1565  (31.4%)          24   (0.5%)     block in Net::SSH::Transport::Session#poll_message
        22   (0.4%)          22   (0.4%)     Net::SSH::Buffer#length
        22   (0.4%)          22   (0.4%)     Net::SSH::Transport::HMAC::Abstract.mac_length
        34   (0.7%)          21   (0.4%)     Net::SSH::Authentication::Agent#read_packet
        20   (0.4%)          20   (0.4%)     Net::SSH::Config.pattern2regex
        28   (0.6%)          20   (0.4%)     Net::SSH::Buffer#read_keyblob
```

According to this profile, when a connection is established, we spend a considerable amount of time parsing known_hosts files.

Looking at the code, it seems they are re-parsed for every connections, so in my case a bit more than 180 times. And it's especially detrimental, because the more servers you connect to, the bigger your known_hosts file is (700ish) in my case. Fortunately, SSHKit does cache those connections, but it would be nice to reduce the CPU consumption here.

I realize in the current API, `KnownHosts#keys_for` is used only from the `KnownHosts. search_in` static method, and therefore caching is complex, but I see 2 possible solutions:

  - Either make that global cache opt-in.
  - Invalidating the cache if the source file mtime changes.

@mfazekas Would any of those 2 proposal be acceptable? I'm willing to submit a PR but I see how it could be refused.

Regards

**Comment by TiagoCardoso1983** [comment]
+1, see https://github.com/net-ssh/net-ssh/issues/232 for a similar issue report.

**Comment by byroot** [comment]
Oh, I skimmed through the issues but totally missed it, reading it now.

**Comment by mfazekas** [comment]
@byroot it's an edge case from net-ssh point of view. I'm not sure how complex that caching would be. We can also modify code so instead of passing ```:user_known_hosts_file``` option you can pass a ```:known_hosts``` object that implements ```keys_in``` and ```add```. Then you can store known hosts in the way you prefer db/cached/etc.

**Comment by byroot** [comment]
> We can also modify code so instead of passing :user_known_hosts_file option you can pass a :known_hosts object that implements keys_in and add

I would be ok with that. I'll try to work on such PR.

**Comment by mfazekas** [comment]
Also before doing anything it would be great to confirm the improvements by just disabling known-host (eg passing ```paranoid: false```)

**Comment by byroot** [comment]
So even with `paranoid: false` the `known_hosts` files are parsed:

```
net-ssh-3.0.2/lib/net/ssh/known_hosts.rb:105:in `keys_for'
net-ssh-3.0.2/lib/net/ssh/known_hosts.rb:37:in `block in search_in'
net-ssh-3.0.2/lib/net/ssh/known_hosts.rb:37:in `map'
net-ssh-3.0.2/lib/net/ssh/known_hosts.rb:37:in `search_in'
net-ssh-3.0.2/lib/net/ssh/known_hosts.rb:31:in `search_for'
net-ssh-3.0.2/lib/net/ssh/transport/algorithms.rb:245:in `prepare_preferred_algorithms!'
net-ssh-3.0.2/lib/net/ssh/transport/algorithms.rb:124:in `initialize'
net-ssh-3.0.2/lib/net/ssh/transport/session.rb:87:in `new'
net-ssh-3.0.2/lib/net/ssh/transport/session.rb:87:in `initialize'
net-ssh-3.0.2/lib/net/ssh.rb:225:in `new'
net-ssh-3.0.2/lib/net/ssh.rb:225:in `start'
```

**Comment by TiagoCardoso1983** [comment]
```paranoid: false``` doesn't work: Try setting these two:

```ruby
...
user_known_hosts_file: [],
global_known_hosts_file: [],
...
```

**Comment by byroot** [comment]
I dirty patched SSHKit to remove `KnownHosts` parsing entirely and here's what I get:

![capture d ecran 2016-02-03 a 13 35 36](https://cloud.githubusercontent.com/assets/44640/12792702/1988bef4-ca7b-11e5-930b-91fd78a5f361.png)

And the profile:

```
==================================
  Mode: wall(1000)
  Samples: 3643 (9.56% miss rate)
  GC: 186 (5.11%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
      1781  (48.9%)        1776  (48.8%)     SSHKit::Runner::Parallel#execute
       350   (9.6%)         350   (9.6%)     Net::SSH::Compat.io_select
       131   (3.6%)         107   (2.9%)     Net::SSH::Transport::Kex::DiffieHellmanGroup1SHA1#send_kexinit
       180   (4.9%)         104   (2.9%)     OpenSSL::PKey::DH#valid?
        76   (2.1%)          76   (2.1%)     block in OpenSSL::PKey::DH#valid?
        73   (2.0%)          73   (2.0%)     block (2 levels) in Net::SSH::Transport::ServerVersion#negotiate!
       193   (5.3%)          45   (1.2%)     Net::SSH::Transport::PacketStream#poll_next_packet
        67   (1.8%)          44   (1.2%)     block in Net::SSH::Config.load
        47   (1.3%)          42   (1.2%)     Net::SSH::Buffer#read
        36   (1.0%)          33   (0.9%)     Net::SSH::Authentication::Agent#read_packet
        29   (0.8%)          29   (0.8%)     Net::SSH::Buffer#write_long
        46   (1.3%)          29   (0.8%)     Net::SSH::BufferedIo#fill
        28   (0.8%)          28   (0.8%)     block (2 levels) in Net::SSH::Connection::Channel#forward_local_env
      1011  (27.8%)          26   (0.7%)     block in Net::SSH::Transport::Session#poll_message
       794  (21.8%)          23   (0.6%)     block in Net::SSH::Transport::Session#wait
        23   (0.6%)          23   (0.6%)     Net::SSH::Transport::HMAC::Abstract.mac_length
        27   (0.7%)          22   (0.6%)     Net::SSH::Transport::State#update_next_iv
        22   (0.6%)          22   (0.6%)     Net::SSH::Buffer#length
        88   (2.4%)          21   (0.6%)     Net::SSH::Config.load
        20   (0.5%)          20   (0.5%)     Net::SSH::Buffer#initialize
        33   (0.9%)          20   (0.5%)     Net::SSH::BufferedIo#send_pending
        20   (0.5%)          20   (0.5%)     Net::SSH::Config.pattern2regex
        19   (0.5%)          19   (0.5%)     Net::SSH::BufferedIo#input
        17   (0.5%)          17   (0.5%)     Logger#debug?
        17   (0.5%)          17   (0.5%)     OpenSSL::PKey::RSA#ssh_do_verify
        16   (0.4%)          16   (0.4%)     Net::SSH::Transport::HMAC::Abstract.digest_class
        15   (0.4%)          15   (0.4%)     Net::SSH::Buffer#to_s
        77   (2.1%)          14   (0.4%)     Net::SSH::Buffer.from
        14   (0.4%)          14   (0.4%)     Net::SSH::Transport::Algorithms#initialized?
        21   (0.6%)          13   (0.4%)     Net::SSH::KeyFactory.load_public_key
```

So IMO that patch would be worth it. But it's your call @mfazekas

**Comment by mfazekas** [comment]
Yes thanks for the results, yes it looks worthwile, yes please submit patch
