### ISSUE TITLE
connection closed by remote host

### ISSUE THREAD

**Issue by radar** [net-ssh/net-ssh#315]
I'm seeing this error pop up frequently with net-ssh 3.0.2 and I have no clue if it's to do with net-ssh, gofer, or the server that I'm connecting to. Here's the stacktrace:

```
/Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/server_version.rb:53:in `rescue in block (2 levels) in negotiate!': connection closed by remote host (Net::SSH::Disconnect)
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/server_version.rb:49:in `block (2 levels) in negotiate!'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/server_version.rb:48:in `loop'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/server_version.rb:48:in `block in negotiate!'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/server_version.rb:46:in `loop'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/server_version.rb:46:in `negotiate!'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/server_version.rb:32:in `initialize'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/session.rb:84:in `new'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/session.rb:84:in `initialize'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh.rb:225:in `new'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh.rb:225:in `start'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/gofer-0.6.0/lib/gofer/ssh_wrapper.rb:33:in `ssh'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/gofer-0.6.0/lib/gofer/ssh_wrapper.rb:15:in `run'
	from /Users/ryanbigg/.gem/ruby/2.3.0/gems/gofer-0.6.0/lib/gofer/host.rb:78:in `exist?'
```

Here's the options passed to `Net::SSH.start`:

```
{:keys=>"/Users/ryanbigg/.ssh/id_rsa", :timeout=>30, :keys_only=>true}
```

Given that the exception is being raised within net-ssh, I would think that it's a net-ssh problem.

Here's the debug stacktrace for net-ssh:

```
D, [2016-03-02T14:06:13.850122 #86816] DEBUG -- net.ssh.transport.session[3fe96687e454]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:13.850430 #86816] DEBUG -- net.ssh.transport.session[3fe96688243c]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:13.851443 #86816] DEBUG -- net.ssh.transport.session[3fe966ca5884]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:13.852760 #86816] DEBUG -- net.ssh.transport.session[3fe966cb56bc]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:13.853259 #86816] DEBUG -- net.ssh.transport.session[3fe966cacfd0]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:13.853732 #86816] DEBUG -- net.ssh.transport.session[3fe966cc9428]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:13.854327 #86816] DEBUG -- net.ssh.transport.session[3fe966cbcaac]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:13.854857 #86816] DEBUG -- net.ssh.transport.session[3fe966cd92c4]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:13.855201 #86816] DEBUG -- net.ssh.transport.session[3fe966cd1920]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:13.855499 #86816] DEBUG -- net.ssh.transport.session[3fe966cd019c]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:13.856291 #86816] DEBUG -- net.ssh.transport.session[3fe966892968]: establishing connection to redacted.server.example.com:22
D, [2016-03-02T14:06:14.581292 #86816] DEBUG -- net.ssh.transport.session[3fe966cd1920]: connection established
I, [2016-03-02T14:06:14.581400 #86816]  INFO -- net.ssh.transport.server_version[3fe966ced788]: negotiating protocol version
D, [2016-03-02T14:06:14.582762 #86816] DEBUG -- net.ssh.transport.session[3fe966cd92c4]: connection established
I, [2016-03-02T14:06:14.582860 #86816]  INFO -- net.ssh.transport.server_version[3fe966cecf04]: negotiating protocol version
D, [2016-03-02T14:06:14.583989 #86816] DEBUG -- net.ssh.transport.session[3fe966cacfd0]: connection established
I, [2016-03-02T14:06:14.584079 #86816]  INFO -- net.ssh.transport.server_version[3fe966cec7ac]: negotiating protocol version
D, [2016-03-02T14:06:14.585189 #86816] DEBUG -- net.ssh.transport.session[3fe966cd019c]: connection established
I, [2016-03-02T14:06:14.585288 #86816]  INFO -- net.ssh.transport.server_version[3fe966ce5d94]: negotiating protocol version
D, [2016-03-02T14:06:14.586382 #86816] DEBUG -- net.ssh.transport.session[3fe96687e454]: connection established
I, [2016-03-02T14:06:14.586479 #86816]  INFO -- net.ssh.transport.server_version[3fe966ce527c]: negotiating protocol version
D, [2016-03-02T14:06:14.587565 #86816] DEBUG -- net.ssh.transport.session[3fe966ca5884]: connection established
I, [2016-03-02T14:06:14.587953 #86816]  INFO -- net.ssh.transport.server_version[3fe96616bfcc]: negotiating protocol version
D, [2016-03-02T14:06:14.588814 #86816] DEBUG -- net.ssh.transport.session[3fe966cc9428]: connection established
I, [2016-03-02T14:06:14.588895 #86816]  INFO -- net.ssh.transport.server_version[3fe96616b874]: negotiating protocol version
D, [2016-03-02T14:06:14.589940 #86816] DEBUG -- net.ssh.transport.session[3fe966892968]: connection established
I, [2016-03-02T14:06:14.590023 #86816]  INFO -- net.ssh.transport.server_version[3fe96616afdc]: negotiating protocol version
D, [2016-03-02T14:06:14.591216 #86816] DEBUG -- net.ssh.transport.session[3fe966cbcaac]: connection established
I, [2016-03-02T14:06:14.591319 #86816]  INFO -- net.ssh.transport.server_version[3fe96616a834]: negotiating protocol version
D, [2016-03-02T14:06:14.592442 #86816] DEBUG -- net.ssh.transport.session[3fe966cb56bc]: connection established
I, [2016-03-02T14:06:14.592537 #86816]  INFO -- net.ssh.transport.server_version[3fe96616a08c]: negotiating protocol version
D, [2016-03-02T14:06:14.593621 #86816] DEBUG -- net.ssh.transport.session[3fe96688243c]: connection established
I, [2016-03-02T14:06:14.593772 #86816]  INFO -- net.ssh.transport.server_version[3fe966cf55a0]: negotiating protocol version
D, [2016-03-02T14:06:14.618097 #86816] DEBUG -- net.ssh.transport.server_version[3fe966ced788]: remote is `SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6'
D, [2016-03-02T14:06:14.618187 #86816] DEBUG -- net.ssh.transport.server_version[3fe966ced788]: local is `SSH-2.0-Ruby/Net::SSH_3.0.2 x86_64-darwin15'
D, [2016-03-02T14:06:14.621472 #86816] DEBUG -- net.ssh.transport.server_version[3fe966cecf04]: remote is `SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6'
D, [2016-03-02T14:06:14.621623 #86816] DEBUG -- net.ssh.transport.server_version[3fe966cecf04]: local is `SSH-2.0-Ruby/Net::SSH_3.0.2 x86_64-darwin15'
/Users/ryanbigg/.gem/ruby/2.3.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/server_version.rb:53:in `rescue in block (2 levels) in negotiate!': connection closed by remote host (Net::SSH::Disconnect)
```

Here's what the `auth.log` has when we can't connect to the server:

```
Mar  2 14:06:14 office sshd[24846]: Did not receive identification string from <ip>
Mar  2 14:06:14 office sshd[24845]: Did not receive identification string from <ip>
Mar  2 14:06:14 office sshd[24847]: Did not receive identification string from <ip>
Mar  2 14:06:14 office sshd[24848]: Did not receive identification string from <ip>
Mar  2 14:06:14 office sshd[24849]: Did not receive identification string from <ip>
Mar  2 14:06:14 office sshd[24850]: Did not receive identification string from <ip>
Mar  2 14:06:14 office sshd[24851]: Did not receive identification string from <ip>
Mar  2 14:06:14 office sshd[24852]: Did not receive identification string from <ip>
```

It'd be great to figure out what's causing this, as it's happening quite a lot when we go to deploy our application.

**Comment by mfazekas** [comment]
@radar what net-ssh reporting to you is that during the negotiation sometime the remote end closes the connection. 
So we send "SSH-2.0-Ruby/Net::SSH_3.0.2 x86_64-darwin15" to server but instead of getting back something the server closes the connection.

What's strange is the ```Did not receive identification string from <ip>``` We now only send our version string once we saw soemthing. Ideally nothing is preventing use from sending our version string first before waiting for others, but i'll look into openssh.

**Comment by mfazekas** [comment]
According to https://github.com/openssh/openssh-portable/blob/ebacd377769ac07d1bf3c75169644336056b7060/sshconnect.c#L564 in SSH2 we can and should send the client id before waiting for server's one.

**Comment by mfazekas** [comment]
So i'll change net-ssh to send id string before waiting for server's one. But this issue is more likely a network connection issue and not a net-ssh issue.

**Comment by mfazekas** [comment]
I've released a 3.1.0beta1 where we send client id before waiting for server to send his. You can try with that, but again, i'm 95% sure it's a networking issue.

I'm now closing the issue, but in case of any new details i'll reopen

**Comment by radar** [comment]
Thanks very much @mfazekas. My team and I will try this out.

**Comment by EdwardCourt** [comment]
I am seeing the same issue as well. I will try the 3.1.0beta1 and look into testing the network for any issues.

**Comment by mfazekas** [comment]
@EdwardCourt please use 3.1.0.rc2

**Comment by EdwardCourt** [comment]
@mfazekas I ran into a different issue testing 3.1.0.rc2, which I opened up a ticket for. I was able to successfully test 3.1.0.rc1 witch fixed the issue for me.
