### ISSUE TITLE
net-ssh-3.1.0.rc2/lib/net/ssh/transport/server_version.rb:44:in `write': Broken pipe (Errno::EPIPE)

### ISSUE THREAD

**Issue by EdwardCourt** [net-ssh/net-ssh#333]
This issue is not present in net-ssh-3.1.0.rc1, not sure what the issue is. 

```
/Users/test/.rvm/gems/ruby-2.3.0/gems/net-ssh-3.1.0.rc2/lib/net/ssh/transport/server_version.rb:44:in `write': Broken pipe (Errno::EPIPE)
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/net-ssh-3.1.0.rc2/lib/net/ssh/transport/server_version.rb:44:in `negotiate!'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/net-ssh-3.1.0.rc2/lib/net/ssh/transport/server_version.rb:32:in `initialize'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/net-ssh-3.1.0.rc2/lib/net/ssh/transport/session.rb:84:in `new'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/net-ssh-3.1.0.rc2/lib/net/ssh/transport/session.rb:84:in `initialize'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/net-ssh-3.1.0.rc2/lib/net/ssh.rb:228:in `new'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/net-ssh-3.1.0.rc2/lib/net/ssh.rb:228:in `start'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/backends/connection_pool.rb:59:in `call'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/backends/connection_pool.rb:59:in `with'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/backends/netssh.rb:134:in `with_ssh'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/backends/netssh.rb:87:in `execute_command'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `block in create_command_and_execute'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `tap'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `create_command_and_execute'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:69:in `execute'
	from TEST.rb:139:in `block in <main>'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:29:in `run'
	from /Users/test/.rvm/gems/ruby-2.3.0/gems/sshkit-1.9.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
```

Code Snippet from TEST.rb
```
SSHKit::Backend::Netssh.configure do |ssh|
  ssh.ssh_options = {
      user: 'ec2-user',
      auth_methods: ['publickey'],
# key value removed. 
      encryption: ["aes128-cbc", "blowfish-cbc", "3des-cbc"],
      forward_agent: false,
      paranoid: Net::SSH::Verifiers::Null.new
  }
end

  on hosts, in: :parallel do |host|
Line 139:    execute "whoami"
  end
```

**Comment by mfazekas** [comment]
There was not difference in 3.1.0.rc1 and 3.1.0.rc2. Can you triple check that this doesn't happen with rc1 and does always happens in rc2?

**Comment by EdwardCourt** [comment]
@mfazekas Thanks for the information. I will try removing all the different ssh-net gem versions installed and test it again.

```
net-ssh (3.1.0.rc2, 3.1.0.rc1, 3.0.2)
```

**Comment by mfazekas** [comment]
FYI it's the same issue as #315 both points to networking issue during version negotiation

**Comment by EdwardCourt** [comment]
@mfazekas I uninstalled all the versions of net-ssh and just installed 3.1.0.rc2 and now the issue is not repeatable. Thank you for the help.
