### ISSUE TITLE
4.0.0.alpha3 windows 10: could not open library '.dll'

### ISSUE THREAD

**Issue by lumean** [net-ssh/net-ssh#357]
Hi,
On win10 I get the following error when trying to load net-ssh 4.0.0.alpha3

```
 (LoadError)223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library '.dll': Das angegebene Modul wurde nicht gefunden.
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium.rb:10:in `extended'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:9:in `extend'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:9:in `<module:Version>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:6:in `<module:Sodium>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:4:in `<module:RbNaCl>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:3:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl.rb:4:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/lib/rbnacl/libsodium.rb:17:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha3/lib/net/ssh/authentication/ed25519.rb:4:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha3/lib/net/ssh/key_factory.rb:3:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha3/lib/net/ssh/authentication/key_manager.rb:2:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha3/lib/net/ssh/authentication/session.rb:4:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha3/lib/net/ssh.rb:11:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from D:/Programming/ruby/commonlibrary/remote_access.rb:2:in `<top (required)>'
        from D:/Programming/ruby/commonlibrary/remote_access_factory.rb:2:in `require_relative'
        from D:/Programming/ruby/commonlibrary/remote_access_factory.rb:2:in `<top (required)>'
        from quick.rb:1:in `require_relative'
        from quick.rb:1:in `<main>'
```

**Comment by mfazekas** [comment]
Thanks much for testing on windows. 
Sounds like an issue in rbnacl-libsodium. Interstingly that line points to: https://github.com/cryptosphere/rbnacl/blob/7947c71657d3aa164650751cb6e5e33dcf23dac9/lib/rbnacl/sodium.rb#L10
which suggests RBNACL_LIBSODIUM_GEM_LIB_PATH is defined but empty???

What is the output of ```gem install rbnacl-libsodium```?

**Comment by lumean** [comment]
```
D:\Programming\ruby\commonlibrary\examples>gem install rbnacl-libsodium
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed rbnacl-libsodium-1.0.10
Parsing documentation for rbnacl-libsodium-1.0.10
Done installing documentation for rbnacl-libsodium after 0 seconds
1 gem installed

D:\Programming\ruby\commonlibrary\examples>
```

**Comment by mfazekas** [comment]
so looks like libsodium path is calculated like:
https://github.com/cryptosphere/rbnacl-libsodium/blob/81461af12e150311ded1e95c55a2e206be61334c/lib/rbnacl/libsodium.rb#L13

Can you try these commands:
```sh
irb
> gem 'rbnacl-libsodium'
> require 'rbnacl/libsodium'
> RBNACL_LIBSODIUM_GEM_LIB_PATH
>spec = Gem::Specification.find_by_name("rbnacl-libsodium")
>Dir.glob(File.join(spec.gem_dir,"vendor/libsodium/dist/lib/*"))
```

**Comment by lumean** [comment]
`irb(main):008:0* gem 'rbnacl-libsodium'
=> true
irb(main):009:0> require 'rbnacl/libsodium'
LoadError: Could not open library '.dll': Das angegebene Modul wurde nicht gefunden.

        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:133:in `block in ffi_lib'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium.rb:10:in `extended'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:9:in `extend'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:9:in `<module:Version>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:6:in `<module:Sodium>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:4:in `<module:RbNaCl>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:3:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl.rb:4:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/lib/rbnacl/libsodium.rb:17:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from (irb):9
        from c:/ruby/ruby223-p173/bin/irb:11:in `<main>'irb(main):010:0>
irb(main):011:0*
irb(main):012:0* RBNACL_LIBSODIUM_GEM_LIB_PATH
=> nil
irb(main):013:0> spec = Gem::Specification.find_by_name("rbnacl-libsodium")
=> #<Gem::Specification:0x19ba56c rbnacl-libsodium-1.0.10>
irb(main):014:0> Dir.glob(File.join(spec.gem_dir,"vendor/libsodium/dist/lib/*"))
=> ["c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/vendor/libsodium/dist/lib/libsodium.a", "c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/vendor/libsodium/dist/lib/libsodium.dll.a", "c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/vendor/libsodium/dist/lib/libsodium.la", "c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/vendor/libsodium/dist/lib/pkgconfig"]
irb(main):015:0>`

**Comment by lumean** [comment]
there is only  libsodium.dll.a   but not libsodium.dll.  If I modify the libsodium file to load .dll.a instead of just .dll I get the following error:

```
irb(main):015:0> require 'rbnacl/libsodium'
c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/vendor/libsodium/dist/lib
c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/lib/rbnacl/libsodium.rb:13: warning: already initialized constant RBNACL_LIBSODIUM_GEM_LIB_PATH
c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/lib/rbnacl/libsodium.rb:13: warning: previous definition of RBNACL_LIBSODIUM_GEM_LIB_PATH was here
c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:7: warning: already initialized constant RbNaCl::Sodium::Version::MINIMUM_LIBSODIUM_VERSION
c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:7: warning: previous definition of MINIMUM_LIBSODIUM_VERSION was here
LoadError: Could not open library 'c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/vendor/libsodium/dist/lib/libsodium.dll.a': T
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:133:in `block in ffi_lib'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium.rb:10:in `extended'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:9:in `extend'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:9:in `<module:Version>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:6:in `<module:Sodium>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:4:in `<module:RbNaCl>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:3:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl.rb:4:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/lib/rbnacl/libsodium.rb:17:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from (irb):15
        from c:/ruby/ruby223-p173/bin/irb:11:in `<main>'irb(main):016:0>
```

**Comment by mfazekas** [comment]
Hi,

Can you also try ```net-ssh 4.0.0.alpha3``` it tries to ignore absence of rbnacl

**Comment by lumean** [comment]
hm, what do you mean? all of this above was already with 4.0.0.alpha3

**Comment by mfazekas** [comment]
Sorry there is an https://rubygems.org/gems/net-ssh/versions/4.0.0.alpha4 too.

**Comment by lumean** [comment]
it's a bit weird, on one PC I get still an error, on the other one I don't:
```
C:\Users\Manuel>gem install net-ssh --pre
Fetching: net-ssh-4.0.0.alpha4.gem (100%)
Successfully installed net-ssh-4.0.0.alpha4
1 gem installed
C:\Users\Manuel>irb
irb(main):001:0> require 'net/ssh'
=> true
irb(main):002:0>
```

```
D:\Programming\ruby\commonlibrary\examples>gem install net-ssh --pre
Fetching: net-ssh-4.0.0.alpha4.gem (100%)
Successfully installed net-ssh-4.0.0.alpha4
Parsing documentation for net-ssh-4.0.0.alpha4
Installing ri documentation for net-ssh-4.0.0.alpha4
Done installing documentation for net-ssh after 4 seconds
1 gem installed
D:\Programming\ruby\commonlibrary\examples>irb
irb(main):001:0> require 'net/ssh'
LoadError: Could not open library '.dll': Das angegebene Modul wurde nicht gefunden.

        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:133:in `block in ffi_lib'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium.rb:10:in `extended'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:9:in `extend'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:9:in `<module:Version>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:6:in `<module:Sodium>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:4:in `<module:RbNaCl>'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:3:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl.rb:4:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.10/lib/rbnacl/libsodium.rb:17:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
... 3 levels...
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha4/lib/net/ssh/key_factory.rb:5:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha4/lib/net/ssh/authentication/key_manager.rb:2:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha4/lib/net/ssh/authentication/session.rb:4:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha4/lib/net/ssh.rb:12:in `<top (required)>'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from c:/ruby/ruby223-p173/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from c:/ruby/ruby223-p173/bin/irb:11:in `<main>'irb(main):002:0>
```

**Comment by lumean** [comment]
Could it be some leftover of rbnacl? On the PC where I get the error I have it installed:
```
D:\Programming\ruby\commonlibrary\examples>gem which rbnacl
c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/rbnacl-3.3.0/lib/rbnacl.rb
```

While on the PC where the require is successful, I don't have it:
```
C:\Users\Manuel>gem which rbnacl
ERROR:  Can't find ruby library file or shared library rbnacl

```

**Comment by lumean** [comment]
When I uninstalled rbnacl, the require was succesful but then when I want to connect to a device I get the following errors:
`c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha4/lib/net/ssh.rb:211:in `start': Value(s) have been set to nil: logger (ArgumentError)`
I assume this is a general change? previous releases allowed me to use net/ssh without specifying a logger.
But when I explicitly specify a logger I get:

```
D, [2016-05-08T16:48:08.980522 #14096] DEBUG -- net.ssh.transport.session[191f304]: establishing connection to 138.187.9.24:22
D, [2016-05-08T16:48:09.016649 #14096] DEBUG -- net.ssh.transport.session[191f304]: connection established
I, [2016-05-08T16:48:09.016649 #14096]  INFO -- net.ssh.transport.server_version[191e668]: negotiating protocol version
D, [2016-05-08T16:48:09.016649 #14096] DEBUG -- net.ssh.transport.server_version[191e668]: local is `SSH-2.0-Ruby/Net::SSH_4.0.0.alpha4 i386-mingw32'
D, [2016-05-08T16:48:09.032272 #14096] DEBUG -- net.ssh.transport.server_version[191e668]: remote is `SSH-2.0-Cisco-1.25'
I, [2016-05-08T16:48:09.047897 #14096]  INFO -- net.ssh.transport.algorithms[191e968]: sending KEXINIT
D, [2016-05-08T16:48:09.047897 #14096] DEBUG -- socket[191eb90]: queueing packet nr 0 type 20 len 1156
D, [2016-05-08T16:48:09.047897 #14096] DEBUG -- socket[191eb90]: sent 1160 bytes

2016-05-08 16:48:09.133 1 DEBUG 'initialize - rescue' Data: Cannot call start if it's negoitation started or done
2016-05-08 16:48:09.148 1 DEBUG 'initialize - rescue' Data: c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha4/lib/net/ssh/transport/algorithms.rb:121:in `start'
c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha4/lib/net/ssh/transport/session.rb:87:in `initialize'
c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha4/lib/net/ssh.rb:241:in `new'
c:/ruby/ruby223-p173/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0.alpha4/lib/net/ssh.rb:241:in `start'


```

**Comment by mfazekas** [comment]
What is the exact code you're using? We should allow logger not to be set, but we do not allow 
```ruby
:logger => nil
```

what is the usecase that causes logger to be nil?

see https://github.com/net-ssh/net-ssh/pull/355

**Comment by lumean** [comment]
I'm using a wrapper around net-ssh where I assign:
`ssh_opts[:logger] = @options["Debug"]`
which worked fine when `@options["Debug"]` was not defined, but since ruby returns nil for an undefined hash key, this code always sets the logger explicitly to nil.
Now I made the assignment conditional on .has_key? so it doesn't fail anymore because of the logger.

**Comment by mfazekas** [comment]
I guess for :logger we should allow nil. @KaneMorgan what do you think?

**Comment by mfazekas** [comment]
:logger 
On the other hand looking at the code, having nil as :logger isn't really supported.

https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh.rb#L219


Like if you do this: ```Net::SSH.start("user","host",logger:nil, verbose: :debug)``` it will crash with 
```ruby
2.3.0 :045 > Net::SSH.start("user","host",logger:nil, verbose: :debug)
NoMethodError: undefined method `level=' for nil:NilClass
from /Users/boga/.rvm/gems/ruby-2.3.0/gems/net-ssh-2.9.4/lib/net/ssh.rb:196:in `start'
...
```

**Comment by KaneMorgan** [comment]
If we want to set a default logger, even if they pass in nil we could move the setter above the code that checks for nils. 

With it not being supported if we changed:
`!options.key?(:logger)` to `!options[:logger]`
 it would catch it being explicitly set to nil as well and set the default in that case.

It looks like password prompts also has a default so it may be worth having a private method set_defaults that gets called before the nil check.

**Comment by mfazekas** [comment]
@KaneMorgan thanks that sounds be the right approach. To have a set_defaults, and check for nil after that, so where we have a default nil makes sense but not otherwise.

**Comment by johnnyshields** [comment]
On Windows 10 using 4.0.0-beta1 I see this error:

```
ArgumentError: Value(s) have been set to nil: password
```

**Comment by KaneMorgan** [comment]
So that comes up when you explicitly set the password to nil in the hash rather than just not setting it.
```
{password:nil}
```
would throw the error but not setting it would be fine.

How are you using it?

**Comment by johnnyshields** [comment]
I'm using it from Capistrano 2. would need to investigate more as to why that's happening.

**Comment by willbryant** [comment]
This affects us too, with cap v2.  Will have to test our other apps to see if they do this anywhere.

Just wondering why it's important to reject nil values?

**Comment by mfazekas** [comment]
@willbryant most of the options are not handling nil values, and it's better to reject them with a nicer message than failing always at later with an ugly error that only fails if we happen to try to use that option.

**Comment by willbryant** [comment]
Makes sense - thanks.

Would you accept a PR to whitelist password, to avoid these regressions?

**Comment by mfazekas** [comment]
@willbryant sure but so far none confirmed if the password: nil is passed by capistrano 2 or it's something you have in your cap files.

**Comment by willbryant** [comment]
Ah right, I did check that myself last night.  Here is the code, in lib/capistrano/ssh.rb:±

```ruby
    def self.connection_strategy(server, options={}, &block)
      methods = [ %w(publickey hostbased), %w(password keyboard-interactive) ]
      password_value = nil
...
      begin
        connection_options = ssh_options.merge(
          :password => password_value,
          :auth_methods => ssh_options[:auth_methods] || methods.shift
        )

        yield host, user, connection_options
      rescue Net::SSH::AuthenticationFailed
        raise if methods.empty? || ssh_options[:auth_methods]
        password_value = options[:password]
        retry
      end
```

**Comment by mfazekas** [comment]
@willbryant did you have time for the capistrano PR?

**Comment by willbryant** [comment]
Thanks for the reminder @mfazekas!  Opened https://github.com/net-ssh/net-ssh/pull/455.
