### ISSUE TITLE
pageant.rb:1:in `require': cannot load such file -- dl/import (LoadError)

### ISSUE THREAD

**Issue by neubi4** [net-ssh/net-ssh#368]
Hi,

i am trying to use "beaker-rspec", uses net-ssh. Running "bundler.bat exec rspec spec/acceptance" gives me the following error messag:
```
» bundler.bat exec rspec spec/acceptance                                                                                                            /cygdrive/c/Users/mtnu/Entwicklung/puppet/amcs_osinventory
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/agent.rb:6: warning: already initialized constant Net::SSH::Authentication::PLATFORM
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/agent.rb:6: warning: previous definition of PLATFORM was here
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/pageant.rb:1:in `require': cannot load such file -- dl/import (LoadError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/pageant.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/agent/socket.rb:5:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/agent/socket.rb:5:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/agent.rb:22:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/agent.rb:22:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/key_manager.rb:4:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/key_manager.rb:4:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/session.rb:4:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/authentication/session.rb:4:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh.rb:11:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.4/lib/net/ssh.rb:11:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-scp-1.2.1/lib/net/scp.rb:4:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-scp-1.2.1/lib/net/scp.rb:4:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/ssh_connection.rb:3:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/ssh_connection.rb:3:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/host.rb:10:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/host.rb:10:in `block in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/host.rb:9:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/host.rb:9:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/test_case.rb:2:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/test_case.rb:2:in `block in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/test_case.rb:1:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/test_case.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/test_suite.rb:5:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/test_suite.rb:5:in `block in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/test_suite.rb:4:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker/test_suite.rb:4:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker.rb:8:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker.rb:8:in `rescue in block in <module:Beaker>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker.rb:5:in `block in <module:Beaker>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker.rb:4:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker.rb:4:in `<module:Beaker>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-2.40.0/lib/beaker.rb:2:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-rspec-5.3.0/lib/beaker-rspec.rb:2:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-rspec-5.3.0/lib/beaker-rspec.rb:2:in `<module:BeakerRSpec>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/beaker-rspec-5.3.0/lib/beaker-rspec.rb:1:in `<top (required)>'
        from C:/Users/mtnu/Entwicklung/puppet/amcs_osinventory/spec/spec_helper_acceptance.rb:1:in `require'
        from C:/Users/mtnu/Entwicklung/puppet/amcs_osinventory/spec/spec_helper_acceptance.rb:1:in `<top (required)>'
        from C:/Users/mtnu/Entwicklung/puppet/amcs_osinventory/spec/acceptance/nodesets/osinventory_spec.rb:1:in `require'
        from C:/Users/mtnu/Entwicklung/puppet/amcs_osinventory/spec/acceptance/nodesets/osinventory_spec.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
        from C:/Ruby22-x64/bin/rspec:23:in `load'
        from C:/Ruby22-x64/bin/rspec:23:in `<main>'
```

i only find solutions wich says use net-ssh 2.9.3-beta1, but beaker-rspec requires 2.9.4. How can i fix this?

OS: Windows7
Ruby: ruby 2.2.4p230
```
» bundler.bat list                                                                                                                                  /cygdrive/c/Users/mtnu/Entwicklung/puppet/amcs_osinventory
Gems included by the bundle:
  * CFPropertyList (2.3.2)
  * addressable (2.4.0)
  * aws-sdk (1.66.0)
  * aws-sdk-v1 (1.66.0)
  * beaker (2.40.0)
  * beaker-answers (0.4.2)
  * beaker-hiera (0.1.1)
  * beaker-pe (0.1.2)
  * beaker-rspec (5.3.0)
  * builder (3.2.2)
  * bundler (1.12.3)
  * diff-lcs (1.2.5)
  * docker-api (1.28.0)
  * excon (0.49.0)
  * faraday (0.9.2)
  * fission (0.5.0)
  * fog (1.34.0)
  * fog-atmos (0.1.0)
  * fog-aws (0.9.2)
  * fog-brightbox (0.10.1)
  * fog-core (1.38.0)
  * fog-dynect (0.0.3)
  * fog-ecloud (0.3.0)
  * fog-google (0.0.9)
  * fog-json (1.0.2)
  * fog-local (0.3.0)
  * fog-powerdns (0.1.1)
  * fog-profitbricks (0.0.5)
  * fog-radosgw (0.0.5)
  * fog-riakcs (0.1.0)
  * fog-sakuracloud (1.7.5)
  * fog-serverlove (0.1.2)
  * fog-softlayer (1.1.1)
  * fog-storm_on_demand (0.1.1)
  * fog-terremark (0.1.0)
  * fog-vmfusion (0.1.0)
  * fog-voxel (0.1.0)
  * fog-xml (0.1.2)
  * formatador (0.2.5)
  * google-api-client (0.9.4)
  * googleauth (0.5.1)
  * hocon (0.9.5)
  * httpclient (2.8.0)
  * hurley (0.2)
  * inflecto (0.0.2)
  * inifile (2.0.2)
  * ipaddress (0.8.3)
  * jruby-pageant (1.1.1)
  * json (1.8.3)
  * jwt (1.5.4)
  * little-plugger (1.1.4)
  * logging (2.1.0)
  * memoist (0.14.0)
  * mime-types (2.99.1)
  * mini_portile2 (2.0.0)
  * minitest (5.8.4)
  * multi_json (1.12.0)
  * multipart-post (2.0.0)
  * net-scp (1.2.1)
  * net-ssh (2.9.4)
  * net-telnet (0.1.1)
  * nokogiri (1.6.7.2)
  * open_uri_redirections (0.2.1)
  * os (0.9.6)
  * rbvmomi (1.8.2)
  * representable (2.3.0)
  * require_all (1.3.3)
  * retriable (2.1.0)
  * rspec (3.4.0)
  * rspec-core (3.4.4)
  * rspec-expectations (3.4.0)
  * rspec-its (1.2.0)
  * rspec-mocks (3.4.1)
  * rspec-support (3.4.1)
  * rsync (1.0.9)
  * serverspec (2.34.0)
  * sfl (2.2)
  * signet (0.7.2)
  * specinfra (2.57.2)
  * stringify-hash (0.0.2)
  * thor (0.19.1)
  * trollop (2.1.2)
  * uber (0.0.15)
  * unf (0.1.4)
  * unf_ext (0.0.7.2)
```

**Comment by mfazekas** [comment]
This should be  fixed in 3.* releases. 
see https://github.com/net-ssh/net-ssh/commit/182ebdf3ca6976306de04bc01b65bf5b36327530
