### ISSUE TITLE
Cannot call start if it's negoitation started or done

### ISSUE THREAD

**Issue by lumean** [net-ssh/net-ssh#416]
Hi,
with the two latest net-ssh versions  3.2.0 and  v4.0.0.beta1 i'm getting the following error when trying to connect to an ubuntu 16.04 server. With version 3.1.1 the script works without any issues.

```
/home/manu/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:129:in `start': Cannot call start if it's negoitation started or done (ArgumentError)
        from /home/manu/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:87:in `initialize'
        from /home/manu/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `new'
        from /home/manu/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `start'
        from /home/manu/programming/commonlibrary/remote_access.rb:325:in `block in initialize'
        from /home/manu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:74:in `timeout'
        from /home/manu/programming/commonlibrary/remote_access.rb:323:in `initialize'
        from /home/manu/programming/commonlibrary/remote_access_factory.rb:81:in `new'
        from /home/manu/programming/commonlibrary/remote_access_factory.rb:81:in `create'
        from quick.rb:15:in `<main>'
```

```
/home/manu/.rvm/gems/ruby-2.3.1/gems/net-ssh-4.0.0.beta1/lib/net/ssh/transport/algorithms.rb:121:in `start': Cannot call start if it's negoitation started or done (ArgumentError)
        from /home/manu/.rvm/gems/ruby-2.3.1/gems/net-ssh-4.0.0.beta1/lib/net/ssh/transport/session.rb:87:in `initialize'
        from /home/manu/.rvm/gems/ruby-2.3.1/gems/net-ssh-4.0.0.beta1/lib/net/ssh.rb:237:in `new'
        from /home/manu/.rvm/gems/ruby-2.3.1/gems/net-ssh-4.0.0.beta1/lib/net/ssh.rb:237:in `start'
        from /home/manu/programming/commonlibrary/remote_access.rb:325:in `block in initialize'
        from /home/manu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:74:in `timeout'
        from /home/manu/programming/commonlibrary/remote_access.rb:323:in `initialize'
        from /home/manu/programming/commonlibrary/remote_access_factory.rb:81:in `new'
        from /home/manu/programming/commonlibrary/remote_access_factory.rb:81:in `create'
        from quick.rb:15:in `<main>'
```

Script contents:

```
require_relative '../remote_access_factory'
require 'logger'

opts_router = {
  "Username" => 'manu',
  "Password" => '******',
  "Transport" => "ssh",
  "Host" => '192.168.1.50',
  #"Timeout" => 3,
  #"Output_log" => "router.log", # uncomment this line to log the session to a file
  #"Debug" => Logger.new(STDOUT)  # uncomment this line to get full debug output
}

session = RemoteAccessFactory.create('linux', opts_router) {|s| puts s.inspect}
a =  session.cmd("String" => "ls -lah", "Timeout" => nil)
puts a

puts session.cmd("date")

session.close

puts "ende gelaende"
```
output of net-ssh 3.1.1:

```
"Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-31-generic x86_64)\n\n * Documentation:  https://help.ubuntu.com\n * Management:     https://landscape.canonical.com\n * Support:        https://ubuntu.com/advantage\n\n0 packages can be updated.\n0 updates are security updates.\n\n*** System restart required ***\nLast login: Wed Aug  3 22:43:31 2016 from 192.168.1.116\r\n"
"\e]0;manu@mpls: ~\amanu@mpls:~$ "
"\n\e]0;manu@mpls: ~\amanu@mpls:~$ "
"stty cols 400\n\e]0;manu@mpls: ~\amanu@mpls:~$ unset PROMPT_COMMAND; PS1='$(date \"+%Y-%m-%d %H:%M:%S\") \\u@\\h\\$'\n2016-08-03 23:41:37 manu@mpls$"
ls -lah
total 308K
drwxr-xr-x 26 manu manu 4.0K  .
drwxr-xr-x  4 root root 4.0K  ..
drwx------  3 manu manu 4.0K  .adobe
drwxr-xr-x  3 manu manu 4.0K  .ansible
CUT  ....
-rw-------  1 manu manu   82  .xsession-errors.old
-rw-rw-r--  1 manu manu  118  .zlogin
-rw-rw-r--  1 manu manu   68  .zshrc
2016-08-03 23:41:37 manu@mpls$
date
Mit Aug  3 23:41:37 CEST 2016
2016-08-03 23:41:37 manu@mpls$
ende gelaende

```

**Comment by lumean** [comment]
if I comment out the raise as well as the kex_init from 
https://github.com/net-ssh/net-ssh/commit/9115c32e93ee574f4f3bfd68252ffc93e485249b
at line 121 and 122
it works again.

**Comment by lumean** [comment]
did some additional analysis, could it be possible that the server sends KEX immediately before we do `@algorithms.start` ?  according to the docs `accept_kexinit(packet)` can be triggered spontaneous and will set `@pending = true`  which then causes `@algorithms.start` to raise

**Comment by mfazekas** [comment]
That is very strange issue:

Where we get the exception from accoring to stacktrace is [this](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/session.rb#L86-L87):
```
@algorithms = Algorithms.new(self, options)
@algorithms.start
```

The first line [set's](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/algorithms.rb#L114) ```@pending = @initialized = false``` so when start checks it should be the same.

**Comment by mfazekas** [comment]
To debug this can you please put this:
```
info { "send_kexinit called from #{caller.join("\n")}" }
```
to 
```ruby-2.3.1/gems/net-ssh-4.0.0.beta1/lib/net/ssh/transport/algorithms.rb``` around line 185 just bellow these [lines](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/algorithms.rb#L183-L184)

**Comment by mfazekas** [comment]
then run the test and post the full trace?

**Comment by lumean** [comment]
found it... it is an issue in my code, sorry for this.
I still had a monkey patch there, which is not anymore compatible with the new releases from net-ssh, namely:
```
# Bugfix for net-ssh gem: Wait for Server version before we send our version.
# this is needed for compatibility with some cisco devices.
# implements: https://github.com/net-ssh/net-ssh/pull/359
# see also: https://github.com/net-ssh/net-ssh/issues/356
module Net; module SSH; module Transport
  class Algorithms
    def initialize(session, options={})
        @session = session
        @logger = session.logger
        @options = options
        @algorithms = {}
        @pending = @initialized = false
        @client_packet = @server_packet = nil
        prepare_preferred_algorithms!
        send_kexinit # send kexinit immediately after version, don't wait for server
    end
  end
end; end; end
```
As soon as I remove that monkeypatch it works (tested with the 4.0.0.beta2):
```
D, [2016-08-10T00:17:03.631119 #1490] DEBUG -- net.ssh.transport.session[3ff7a9cec4a4]: establishing connection to 192.168.1.50:22
D, [2016-08-10T00:17:03.640361 #1490] DEBUG -- net.ssh.transport.session[3ff7a9cec4a4]: connection established
I, [2016-08-10T00:17:03.640594 #1490]  INFO -- net.ssh.transport.server_version[3ff7a9ce98f8]: negotiating protocol version
D, [2016-08-10T00:17:03.640660 #1490] DEBUG -- net.ssh.transport.server_version[3ff7a9ce98f8]: local is `SSH-2.0-Ruby/Net::SSH_4.0.0.beta2 x86_64-darwin15'
D, [2016-08-10T00:17:03.669746 #1490] DEBUG -- net.ssh.transport.server_version[3ff7a9ce98f8]: remote is `SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu1'
I, [2016-08-10T00:17:03.671071 #1490]  INFO -- net.ssh.transport.algorithms[3ff7a9ce8250]: sending KEXINIT
I, [2016-08-10T00:17:03.671200 #1490]  INFO -- net.ssh.transport.algorithms[3ff7a9ce8250]: send_kexinit called from /Users/manuelwidmer/.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh/loggable.rb:31:in `block in info'
.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/logger.rb:372:in `add'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh/loggable.rb:31:in `info'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh/transport/algorithms.rb:186:in `send_kexinit'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh/transport/algorithms.rb:122:in `start'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh/transport/session.rb:87:in `initialize'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh.rb:237:in `new'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh.rb:237:in `start'
programming/commonlibrary/remote_access.rb:325:in `block in initialize'
.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
programming/commonlibrary/remote_access.rb:323:in `initialize'
programming/commonlibrary/remote_access_factory.rb:81:in `new'
programming/commonlibrary/remote_access_factory.rb:81:in `create'
quick.rb:15:in `<main>'
D, [2016-08-10T00:17:03.671506 #1490] DEBUG -- socket[3ff7a9ced0d4]: queueing packet nr 0 type 20 len 1156
D, [2016-08-10T00:17:03.671618 #1490] DEBUG -- socket[3ff7a9ced0d4]: sent 1160 bytes
D, [2016-08-10T00:17:03.671728 #1490] DEBUG -- socket[3ff7a9ced0d4]: read 976 bytes
D, [2016-08-10T00:17:03.671819 #1490] DEBUG -- socket[3ff7a9ced0d4]: received packet nr 0 type 20 len 972
I, [2016-08-10T00:17:03.671874 #1490]  INFO -- net.ssh.transport.algorithms[3ff7a9ce8250]: got KEXINIT from server
I, [2016-08-10T00:17:03.672047 #1490]  INFO -- net.ssh.transport.algorithms[3ff7a9ce8250]: negotiating algorithms
...
```

Whereas before kex_init was called directly from `algorithms.initialize` instead of `algorithms.start`
```
I, [2016-08-10T00:12:49.675915 #1479]  INFO -- net.ssh.transport.server_version[3fe38149e734]: negotiating protocol version
D, [2016-08-10T00:12:49.675950 #1479] DEBUG -- net.ssh.transport.server_version[3fe38149e734]: local is `SSH-2.0-Ruby/Net::SSH_4.0.0.beta2 x86_64-darwin15'
D, [2016-08-10T00:12:49.706382 #1479] DEBUG -- net.ssh.transport.server_version[3fe38149e734]: remote is `SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu1'
I, [2016-08-10T00:12:49.707455 #1479]  INFO -- net.ssh.transport.algorithms[3fe38149b6ec]: sending KEXINIT
I, [2016-08-10T00:12:49.707553 #1479]  INFO -- net.ssh.transport.algorithms[3fe38149b6ec]: send_kexinit called from /Users/manuelwidmer/.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh/loggable.rb:31:in `block in info'
.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/logger.rb:372:in `add'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh/loggable.rb:31:in `info'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh/transport/algorithms.rb:186:in `send_kexinit'
programming/commonlibrary/remote_access.rb:75:in `initialize'  <<<< here is the monkeypatch with Algorithms#initialize
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh/transport/session.rb:86:in `new'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh/transport/session.rb:86:in `initialize'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh.rb:237:in `new'
.rvm/gems/ruby-2.2.4/gems/net-ssh-4.0.0.beta2/lib/net/ssh.rb:237:in `start'

```
I think we can close this issue.
