### ISSUE TITLE
ssh.exec! block version does not return complete output

### ISSUE THREAD

**Issue by spurnaye** [net-ssh/net-ssh#446]
Hello team,
I have a script that generates output after time delay
example:
/somescript.sh
```
echo "start of output"
sleep(3)
echo "end of output"
```

With ssh.exec! used as follows prints only the last executed line that is "end of output"
```
ssh = Net::SSH.start(hostname, username)
ssh.exec!('somescript.sh') do |channel, stream, data|
        puts data # "end of output"
      end
```
Please let me know if I need to activate any configurations to get the entire output.

**Comment by mfazekas** [comment]
what is your net-ssh version?

this script
```ruby
gem 'net-ssh', '= 2.9.4'
require 'net/ssh'
#require 'byebug'
puts Net::SSH::Version::CURRENT

@host = 'localhost'
@user = ENV['USER']
Net::SSH.start(@host, @user) do |ssh|
  puts "==> try 1"
  puts ssh.exec!('echo "start of output" ; sleep 3 ; echo "end of output"')
  puts "==> try 2"
  ssh.exec!('echo "start of output" ; sleep 3 ; echo "end of output"') { |ch,type,data|
    puts "data:#{data}"
  }
end

puts "Done!"
```

output:

```sh
2.9.4
/Users/boga/.rvm/gems/ruby-2.3.1/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/boga/.rvm/gems/ruby-2.3.1/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
==> try 1
start of output
end of output
==> try 2
data:start of output
data:end of output
```

works for me as expected
