### ISSUE TITLE
request_pty breaks send_data->eof!->close [sample code provided]

### ISSUE THREAD

**Issue by Sod-Almighty** [net-ssh/net-ssh#460]
### Expected behavior

When using `send_data` followed by `eof!`, the data should be sent to the server and the channel closed. The server process - e.g. `tee` - should notice that `stdin` has closed (as if the user pressed `CTRL-D` at the console) and immediately exit.

If `request_pty` is omitted, this problem does not occur. **However, `request_pty` is needed, because in the real project I am using `sudo`.** Without a pty, `sudo` would - as I understand it - refuse to accept the password via stdin.

### Actual behavior

If `close` is explicitly called after `eof!`, the ssh loop terminates immediately without sending the data. If `close` is _not_ explicitly called, the ssh loop hangs indefinitely, waiting for the server process to terminate (which `tee` won't do until stdin is properly closed). Upon issuing a CTRL-C at the console, the following stack trace is shown:

```
/usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/ruby_compat.rb:25:in `select': Interrupt
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/ruby_compat.rb:25:in `io_select'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:210:in `process'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `loop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `loop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/channel.rb:269:in `wait'
	from ./ssh-test.rb:27:in `block (2 levels) in <main>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/channel.rb:530:in `do_open_confirmation'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:572:in `channel_open_confirmation'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:479:in `dispatch_incoming_packets'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:225:in `preprocess'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:206:in `process'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `loop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `loop'
	from ./ssh-test.rb:30:in `block in <main>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh.rb:240:in `start'
	from ./ssh-test.rb:10:in `<main>'
```

### System configuration

net-ssh (3.2.0)
ruby 2.3.0p71 (2016-03-30 revision 54426) [x86_64-linux]
Debian 8 64-bit (client)
Debian 7 64-bit (server)

### Example Code

You will need to change HOST, USER, PASSWORD and FILENAME to match your system.

Change EXPLICIT_CLOSE and/or PTY to change the behaviour of the example. The example works without PTY, but I kinda need to use that. With EXPLICIT_CLOSE, no data is written to the server. Without EXPLICIT_CLOSE, the `ssh.loop` call never terminates.

```ruby
DATA = "test string"
EXPLICIT_CLOSE = false
HOST = '10.0.0.164'
USER = 'user'
PASSWORD = 'password'
FILENAME = '/home/user/test-file'
PTY = true

require 'net/ssh'

Net::SSH.start(HOST, USER, :password => PASSWORD) do |ssh|
  exit_status = nil
  ssh.open_channel do |channel|
    channel.on_request "exit-status" do |channel, data|
      exit_status = data.read_long
    end
    channel.request_pty if PTY
    channel.exec("tee %s" % FILENAME) do |channel, success|
      if success
        channel.on_data { |channel, data| print data }
        channel.send_data DATA + ?\n
        channel.eof!
        channel.close if EXPLICIT_CLOSE
      else
        puts "FAILED"; exit 1
      end
    end
    channel.wait
    puts exit_status
  end
  ssh.loop
end
```

Oddly, the behaviour is not 100% consistent. I'm fairly sure it works *occasionally*.

**Comment by mfazekas** [comment]
@Sod-Almighty  Thanks much for the awesome detailed report 👍 , can you try with `4.0.0rc1`?

**Comment by Sod-Almighty** [comment]
I just now tested it with `4.4.0rc1`. The problem remains.

**Comment by mfazekas** [comment]
Adding `verbose: :debug` shows that we do send the `eof`. Somehow when in pty mode eof is not passed to the process.

```log
D, [2016-12-10T09:20:25.496208 #24059] DEBUG -- socket[3feac19147b8]: queueing packet nr 13 type 96 len 28
D, [2016-12-10T09:20:25.496345 #24059] DEBUG -- socket[3feac19147b8]: sent 120 bytes
```

Also when adding close i do see the correct order:
```
queueing packet nr 12 type 94 len 44
D, [2016-12-10T09:33:13.035141 #24893] DEBUG -- socket[3fd19a010788]: queueing packet nr 13 type 96 len 28
D, [2016-12-10T09:33:13.035300 #24893] DEBUG -- socket[3fd19a010788]: queueing packet nr 14 type 97 len 28
```

Also if i add a sleep before ```send_data``` then close solution does seems to work, strange...

Need to look into what happens differently in openssh ```ssh -vvv user@localhost -t -C "sudo ls"```

**Comment by Sod-Almighty** [comment]
4 months now. No movement on this issue?

**Comment by grzesiek** [comment]
I've run into this today, so far no luck with making it work :thinking:

**Comment by infinity-computers-dot-net** [comment]
After **FOUR GODDAMN YEARS**, I think we can safely say the author doesn't give a **flying damn** about it. Give up, find another library.

**Comment by mfazekas** [comment]
> After **FOUR GODDAMN YEARS**, I think we can safely say the author doesn't give a **flying damn** about it. Give up, find another library.

Not sure what's the point of this comment. Note that the author [left](https://weblog.jamisbuck.org/2009/2/24/net-ssh-capistrano-and-saying-goodbye.html) the project a long time ago. Also, note that the maintainers are spending their free time to work on this library, and such comments will not help in any way.

We always welcome contributions.

**Comment by infinity-computers-dot-net** [comment]
> Note that the author left the project a long time ago

Then clearly he doesn't care about the project. Which is exactly what I said.

Anyway, if the maintainers haven't been able (or inclined) to fix this **serious bug that renders the library almost useless** in such a long amount of time, I have to wonder what the point of maintaining it actually _is._

**Comment by fwininger** [comment]
@infinity-computers-dot-net given the number of contributions you have on your account, I imagine that correcting the problem is too difficult for you?

Open source does not mean free. If you are not able to contribute technically to the open source software that you use, I invite you to pay so that other people can do the job for you. I know of freelance developers who can fix this problem if you want.

If you can't contribute in any way, I suggest you go to another project.

**Comment by stillhart** [comment]
@infinity-computers-dot-net Are you aware that Net::SSH has over 131'400'000 Downloads on rubygems.org and over 81'000 Packages depend on it on Github? I do not think that this bug renders the library for all those people almost useless.

If you wish that this bug or other bugs in this project get resolved faster, you might start [sponsoring net-ssh](https://opencollective.com/net-ssh#sponsor) or paying a freelancer to create a merge request with a bugfix. You can contribute to this community project, you don't need to be a ruby developer to do so. If this bug creates any costs for you, it should be easy to pay somebody to create a bugfix. Why not be a part of the solution of your problem?

**Comment by infinity-computers-dot-net** [comment]
Well, one of the many reasons is, I already found an alternative library three years ago that doesn't suffer from this issue.

Another reason is, I would never sponsor a development team that are prepared to leave a serious bug unaddressed for almost four years.

**Comment by fwininger** [comment]
I am glad that you have found an alternative that meets your needs.

**Comment by fwininger** [comment]
We will be able to start a technical discussion on this thread.

**Comment by grzesiek** [comment]
My comment wan't meant to start this unhealthy discussion, I really appreciate all the efforts maintainers are putting into working on this library :purple_heart: 

For what it is worth, I managed to find a workaround for this bug, and apparently what I've been affected by is not a bug at all, probably it was more close to a feature than a bug :smile: 

My problem was indeed a little different - when you `request_pty` you no longer can send data that is not terminated with a new line character `"\n"`.  Solution here is to simply add a line character, but if you depend on sending partial data (like prompt-like output) you can no longer use `request_pty`. And this is probably understandable because the new line character is LF / linefeed control character used in PTYs.
