### ISSUE TITLE
When unsupported algorithms are encountered, an exception is thrown due to interpolating a non-existant variable

### ISSUE THREAD

**Issue by greenantdotcom** [net-ssh/net-ssh#483]
### Expected behavior

`net-ssh` would connect to the upstream server regardless of log verbosity.

### Actual behavior

Upon attempting to connect to an upstream server in debug mode, the code raises an **undefined local variable or method** `NameError`.

connecting to an upstream server in debug mode, an exception would be encountered…

```
✔ 20:40 ~ $ ruby /tmp/fun.rb
4.0.1
D, [2017-01-07T20:41:02.470255 #47938] DEBUG -- net.ssh.transport.session[3feaaf08f938]: establishing connection to localhost:22
D, [2017-01-07T20:41:02.472738 #47938] DEBUG -- net.ssh.transport.session[3feaaf08f938]: connection established
I, [2017-01-07T20:41:02.472808 #47938]  INFO -- net.ssh.transport.server_version[3feaaf08bc48]: negotiating protocol version
D, [2017-01-07T20:41:02.472828 #47938] DEBUG -- net.ssh.transport.server_version[3feaaf08bc48]: local is `SSH-2.0-Ruby/Net::SSH_4.0.1 x86_64-darwin15'
D, [2017-01-07T20:41:02.490378 #47938] DEBUG -- net.ssh.transport.server_version[3feaaf08bc48]: remote is `SSH-2.0-OpenSSH_7.3'
/Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/transport/algorithms.rb:266:in `block in compose_algorithm_list': undefined local variable or method `algorithm' for #<Net::SSH::Transport::Algorithms:0x007fd55e10f438> (NameError)
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/loggable.rb:37:in `block in lwarn'
	from /Users/mhughes5/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/logger.rb:372:in `add'
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/loggable.rb:37:in `lwarn'
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/transport/algorithms.rb:266:in `compose_algorithm_list'
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/transport/algorithms.rb:215:in `block in prepare_preferred_algorithms!'
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/transport/algorithms.rb:214:in `each'
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/transport/algorithms.rb:214:in `prepare_preferred_algorithms!'
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/transport/algorithms.rb:119:in `initialize'
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/transport/session.rb:86:in `new'
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/transport/session.rb:86:in `initialize'
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh.rb:233:in `new'
	from /Users/mhughes5/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh.rb:233:in `start'
	from /tmp/fun.rb:6:in `<main>'
```

### System configuration

- net-ssh 4.0.1
- Ruby - ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]
- macOS Sierra 10.12.2

### Example App

```ruby
gem 'net-ssh'
require 'net/ssh'

puts Net::SSH::Version::CURRENT

Net::SSH.start('localhost', 'username', :verbose => :debug) do |ssh|
  # capture all stderr and stdout output from a remote process
  output = ssh.exec!("hostname")
  puts output
end
```

### Underlying Issue

The raised exception refers to an interpolation of a variable `algorithm` which does not exist.

**Comment by greenantdotcom** [comment]
Fix, plus verification test, submitted in https://github.com/net-ssh/net-ssh/pull/484
