### ISSUE TITLE
Unable to bootstrap chef node using "knife" due to net-ssh requiring gems

### ISSUE THREAD

**Issue by mwalters12** [net-ssh/net-ssh#521]
### Expected behavior

I should be able to bootstrap a node into the chef server.

### Actual behavior

I run into an error message and the command fails. 

### System configuration

- net-ssh version: (4.1.0)
- Ruby version: 2.3.1p112 (2016-04-26 revision 54768)

### Example App

```
knife bootstrap -N dev-chefnode.example.com dev-chefnode.example.com -x admin -i ..\.ssh\admin-private.pem --sudo
C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:10: warning: already initialized constant RbNaCl::Sodium::Version::MINIMUM_LIBSODIUM_VERSION
C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:10: warning: previous definition of MINIMUM_LIBSODIUM_VERSION was here
C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:11: warning: already initialized constant RbNaCl::Sodium::Version::MINIMUM_LIBSODIUM_VERSION_FOR_ARGON2
C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:11: warning: previous definition of MINIMUM_LIBSODIUM_VERSION_FOR_ARGON2 was here
Creating new client for dev-chefnode.example.com
Creating new node for dev-chefnode.example.com
Connecting to dev-chefnode.example.com
ERROR: NotImplementedError: OpenSSH keys only supported if ED25519 is available
net-ssh requires the following gems for ed25519 support:
 * rbnacl (>= 3.2, < 5.0)
 * rbnacl-libsodium, if your system doesn't have libsodium installed.
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/478 for more information
LoadError : "Could not open library '.dll': The specified module could not be found.
"
```

**Comment by mfazekas** [comment]
Do you have libsodium installed on the windows system?

https://github.com/cryptosphere/rbnacl/wiki/Windows-Installation

**Comment by mwalters12** [comment]
Sorry about that, I forgot to include proof I do have those 3 packages installed:

`
gem list
rbnacl (4.0.2)
rbnacl-libsodium (1.0.11)
bcrypt_pbkdf (1.0.0 x86-mingw32)
`

Would this mean I have "libsodium" if I had the "rbacl-libsodium"?

Thank you for the response.

**Comment by mfazekas** [comment]
Yes ideally rbnacl-libsodium would install .dll, but i think it was somehow not built correctly. Can you do the following:

```
irb
2.4.0 :001 > require 'rbnacl'
```

**Comment by mwalters12** [comment]
Here is the output:

```
require 'rbnacl'
LoadError: Could not open library 'sodium': The specified module could not be found.
.
Could not open library 'sodium.dll': The specified module could not be found.

        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium.rb:14:in `extended'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:13:in `extend'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:13:in `<module:Version>'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:9:in `<module:Sodium>'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:7:in `<module:RbNaCl>'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:6:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl.rb:6:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from C:/opscode/chefdk/embedded/bin/irb.cmd:19:in `<main>'
```

I suppose I should install your method from above?

**Comment by mfazekas** [comment]
What is the output of this?
```
irb
2.4.0 :006 > gem 'rbnacl-libsodium'
2.4.0 :007 > require 'rbnacl'
```

**Comment by mwalters12** [comment]
```
irb

irb(main):001:0> gem 'rbnacl-libsodium'
=> true

irb(main):002:0> require 'rbnacl'
LoadError: Could not open library 'sodium': The specified module could not be found.
.
Could not open library 'sodium.dll': The specified module could not be found.

        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium.rb:14:in `extended'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:13:in `extend'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:13:in `<module:Version>'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:9:in `<module:Sodium>'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:7:in `<module:RbNaCl>'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:6:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Users/USER/AppData/Local/chefdk/gem/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl.rb:6:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from (irb):2
        from C:/opscode/chefdk/embedded/bin/irb.cmd:19:in `<main>'
```

**Comment by mwalters12** [comment]
Any other ideas?

**Comment by mfazekas** [comment]
Sorry the above means that your `rbnacl` is not installed correctly.

Have you tried the instruction at:
https://github.com/cryptosphere/rbnacl/wiki/Windows-Installation

could you get it work that way?

**Comment by mwalters12** [comment]
I guess I should just setup a linux box for this workstation.  I am getting now where with this issue :(

```
::RBNACL_LIBSODIUM_GEM_LIB_PATH = "C:\Users\USER\Downloads\libsodium-1.0.12-msvc\Win32\Release\v120\dynamic\libsodium.dll"
::RBNACL_LIBSODIUM_GEM_LIB_PATH : The term '::RBNACL_LIBSODIUM_GEM_LIB_PATH' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ::RBNACL_LIBSODIUM_GEM_LIB_PATH = "C:\Users\USER\Downloads\libsodium-1.0.12-m ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (::RBNACL_LIBSODIUM_GEM_LIB_PATH:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I am running this with Powershell as Administrator. Any other thoughts?

**Comment by mfazekas** [comment]
I'm closing the issue for now. Will be reopening it on further input.
