### ISSUE TITLE
IOError Closed stream with 4.2.0.rc1

### ISSUE THREAD

**Issue by tfluehmann** [net-ssh/net-ssh#536]
### Expected behavior

Until now we always got the following exception when we gave wrong credentials for login:
Net::SSH::AuthenticationFailed: Authentication failed for user <user>

### Actual behavior

Since Version 4.2.0-rc01 we get an IOError closed stream exception when we give wrong credentials for login.
```ruby
IOError: closed stream
from /.bundle/ruby/2.2.0/gems/net-ssh-4.2.0.rc1/lib/net/ssh/transport/session.rb:128:in `close'
```
Our app needs to distinguish between wrong credentials and a network interruption.

### System configuration

- net-ssh version: 4.2.0-rc01
- Ruby version: ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]

### Example App

You can use this as stating point:

```ruby
gem 'net-ssh', '= 4.2.0.rc1'
require 'net/ssh'
puts Net::SSH::Version::CURRENT

@host = 'localhost'
@user = ENV['USER']
Net::SSH.start(@host, @user, password: "<your_possibly_wrong_password>", non_interactive: true)
```

**Comment by mfazekas** [comment]
Thanks for the detailed bugreport. Can you post the full stacktrace? I was not able to reproduce the issue for the first attempt:

```ruby
require 'net/ssh'
puts Net::SSH::Version::CURRENT

@host = 'localhost'
@user = ENV['USER']
Net::SSH.start(@host, @user, password: 'wrong', non_interactive: true, auth_methods: ['keyboard-interactive'])
```

Output was:
```
require 'net/ssh'
puts Net::SSH::Version::CURRENT

@host = 'localhost'
@user = ENV['USER']
Net::SSH.start(@host, @user, password: 'wrong', non_interactive: true, auth_methods: ['keyboard-interactive'])
```

**Comment by mfazekas** [comment]
Also adding `verbose: :debug` could help to see what's going on.

**Comment by tfluehmann** [comment]
My fault, on localhost it does not take into account the credentials, since you are already logged in.
I tried it with a different host, and there I get the following output: 

#Expected behaviour (tested with net-ssh 4.1)
```ruby
[2] pry(main)> Net::SSH.start("remote_machine", "user", password: "crap", non_interactive: true, verbose: :debug)
D, [2017-07-17T12:18:10.171549 #30911] DEBUG -- net.ssh.transport.session[3fb605fb7a48]: establishing connection to remote_machine:22
D, [2017-07-17T12:18:10.208882 #30911] DEBUG -- net.ssh.transport.session[3fb605fb7a48]: connection established
I, [2017-07-17T12:18:10.208995 #30911]  INFO -- net.ssh.transport.server_version[3fb605fb6ecc]: negotiating protocol version
D, [2017-07-17T12:18:10.209041 #30911] DEBUG -- net.ssh.transport.server_version[3fb605fb6ecc]: local is `SSH-2.0-Ruby/Net::SSH_4.1.0 x86_64-linux'
D, [2017-07-17T12:18:10.305099 #30911] DEBUG -- net.ssh.transport.server_version[3fb605fb6ecc]: remote is `SSH-2.0-Cisco-2.0'
I, [2017-07-17T12:18:10.307929 #30911]  INFO -- net.ssh.transport.algorithms[3fb605fb7c8c]: sending KEXINIT
D, [2017-07-17T12:18:10.308214 #30911] DEBUG -- socket[3fb605fb73f4]: queueing packet nr 0 type 20 len 1156
D, [2017-07-17T12:18:10.308287 #30911] DEBUG -- socket[3fb605fb73f4]: sent 1160 bytes
D, [2017-07-17T12:18:10.312954 #30911] DEBUG -- socket[3fb605fb73f4]: read 240 bytes
D, [2017-07-17T12:18:10.313105 #30911] DEBUG -- socket[3fb605fb73f4]: received packet nr 0 type 20 len 236
I, [2017-07-17T12:18:10.313183 #30911]  INFO -- net.ssh.transport.algorithms[3fb605fb7c8c]: got KEXINIT from server
I, [2017-07-17T12:18:10.313263 #30911]  INFO -- net.ssh.transport.algorithms[3fb605fb7c8c]: negotiating algorithms
D, [2017-07-17T12:18:10.313367 #30911] DEBUG -- net.ssh.transport.algorithms[3fb605fb7c8c]: negotiated:
* kex: diffie-hellman-group1-sha1
* host_key: ssh-rsa
* encryption_server: aes128-cbc
* encryption_client: aes128-cbc
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client:
* language_server:
D, [2017-07-17T12:18:10.313405 #30911] DEBUG -- net.ssh.transport.algorithms[3fb605fb7c8c]: exchanging keys
D, [2017-07-17T12:18:10.315738 #30911] DEBUG -- socket[3fb605fb73f4]: queueing packet nr 1 type 30 len 140
D, [2017-07-17T12:18:10.315788 #30911] DEBUG -- socket[3fb605fb73f4]: sent 144 bytes
D, [2017-07-17T12:18:10.671409 #30911] DEBUG -- socket[3fb605fb73f4]: read 704 bytes
D, [2017-07-17T12:18:10.671571 #30911] DEBUG -- socket[3fb605fb73f4]: received packet nr 1 type 31 len 700
D, [2017-07-17T12:18:10.672568 #30911] DEBUG -- socket[3fb605fb73f4]: queueing packet nr 2 type 21 len 20
D, [2017-07-17T12:18:10.672633 #30911] DEBUG -- socket[3fb605fb73f4]: sent 24 bytes
D, [2017-07-17T12:18:10.679247 #30911] DEBUG -- socket[3fb605fb73f4]: read 16 bytes
D, [2017-07-17T12:18:10.679314 #30911] DEBUG -- socket[3fb605fb73f4]: received packet nr 2 type 21 len 12
D, [2017-07-17T12:18:10.679685 #30911] DEBUG -- net.ssh.authentication.session[3fb605f42248]: beginning authentication of `user'
D, [2017-07-17T12:18:10.679836 #30911] DEBUG -- socket[3fb605fb73f4]: queueing packet nr 3 type 5 len 28
D, [2017-07-17T12:18:10.679879 #30911] DEBUG -- socket[3fb605fb73f4]: sent 52 bytes
D, [2017-07-17T12:18:10.890607 #30911] DEBUG -- socket[3fb605fb73f4]: read 52 bytes
D, [2017-07-17T12:18:10.890817 #30911] DEBUG -- socket[3fb605fb73f4]: received packet nr 3 type 6 len 28
D, [2017-07-17T12:18:10.891254 #30911] DEBUG -- net.ssh.authentication.session[3fb605f42248]: trying none
D, [2017-07-17T12:18:10.891415 #30911] DEBUG -- socket[3fb605fb73f4]: queueing packet nr 4 type 50 len 44
D, [2017-07-17T12:18:10.891479 #30911] DEBUG -- socket[3fb605fb73f4]: sent 68 bytes
D, [2017-07-17T12:18:10.913663 #30911] DEBUG -- socket[3fb605fb73f4]: read 52 bytes
D, [2017-07-17T12:18:10.913778 #30911] DEBUG -- socket[3fb605fb73f4]: received packet nr 4 type 51 len 28
D, [2017-07-17T12:18:10.913842 #30911] DEBUG -- net.ssh.authentication.session[3fb605f42248]: allowed methods: password
D, [2017-07-17T12:18:10.913913 #30911] DEBUG -- net.ssh.authentication.methods.none[3fb608f6e994]: none failed
D, [2017-07-17T12:18:10.913998 #30911] DEBUG -- net.ssh.authentication.session[3fb605f42248]: trying password
D, [2017-07-17T12:18:10.914207 #30911] DEBUG -- socket[3fb605fb73f4]: queueing packet nr 5 type 50 len 60
D, [2017-07-17T12:18:10.914271 #30911] DEBUG -- socket[3fb605fb73f4]: sent 84 bytes
D, [2017-07-17T12:18:11.040305 #30911] DEBUG -- socket[3fb605fb73f4]: read 68 bytes
D, [2017-07-17T12:18:11.040508 #30911] DEBUG -- socket[3fb605fb73f4]: received packet nr 5 type 53 len 44
I, [2017-07-17T12:18:11.040588 #30911]  INFO -- net.ssh.authentication.session[3fb605f42248]: Password incorrect.


D, [2017-07-17T12:18:11.091070 #30911] DEBUG -- socket[3fb605fb73f4]: read 52 bytes
D, [2017-07-17T12:18:11.091218 #30911] DEBUG -- socket[3fb605fb73f4]: received packet nr 6 type 51 len 28
D, [2017-07-17T12:18:11.091299 #30911] DEBUG -- net.ssh.authentication.session[3fb605f42248]: allowed methods: password
D, [2017-07-17T12:18:11.091384 #30911] DEBUG -- net.ssh.authentication.methods.password[3fb608f77ae4]: password failed
E, [2017-07-17T12:18:11.091436 #30911] ERROR -- net.ssh.authentication.session[3fb605f42248]: all authorization methods failed (tried none, password)
Net::SSH::AuthenticationFailed: Authentication failed for user user@remote_machine
from .bundle/ruby/2.2.0/gems/net-ssh-4.1.0/lib/net/ssh.rb:250:in `start'
```

Actual behaviour (net-ssh 4.2.0-rc01)
```ruby
[1] pry(main)> Net::SSH.start("remote_machine", "user", password: "crap", non_interactive: true, verbose: :debug)
D, [2017-07-17T12:19:38.269670 #61274] DEBUG -- net.ssh.transport.session[3f9ecf7ccec0]: establishing connection to remote_machine:22
D, [2017-07-17T12:19:38.310855 #61274] DEBUG -- net.ssh.transport.session[3f9ecf7ccec0]: connection established
I, [2017-07-17T12:19:38.310977 #61274]  INFO -- net.ssh.transport.server_version[3f9ecf7cd8fc]: negotiating protocol version
D, [2017-07-17T12:19:38.311011 #61274] DEBUG -- net.ssh.transport.server_version[3f9ecf7cd8fc]: local is `SSH-2.0-Ruby/Net::SSH_4.2.0.rc1 x86_64-linux'
D, [2017-07-17T12:19:38.413677 #61274] DEBUG -- net.ssh.transport.server_version[3f9ecf7cd8fc]: remote is `SSH-2.0-Cisco-2.0'
I, [2017-07-17T12:19:38.452233 #61274]  INFO -- net.ssh.transport.algorithms[3f9ed39d9868]: sending KEXINIT
D, [2017-07-17T12:19:38.452466 #61274] DEBUG -- socket[3f9ecf7cc77c]: queueing packet nr 0 type 20 len 1156
D, [2017-07-17T12:19:38.452547 #61274] DEBUG -- socket[3f9ecf7cc77c]: sent 1160 bytes
D, [2017-07-17T12:19:38.452643 #61274] DEBUG -- socket[3f9ecf7cc77c]: read 240 bytes
D, [2017-07-17T12:19:38.452759 #61274] DEBUG -- socket[3f9ecf7cc77c]: received packet nr 0 type 20 len 236
I, [2017-07-17T12:19:38.452848 #61274]  INFO -- net.ssh.transport.algorithms[3f9ed39d9868]: got KEXINIT from server
I, [2017-07-17T12:19:38.452947 #61274]  INFO -- net.ssh.transport.algorithms[3f9ed39d9868]: negotiating algorithms
D, [2017-07-17T12:19:38.453066 #61274] DEBUG -- net.ssh.transport.algorithms[3f9ed39d9868]: negotiated:
* kex: diffie-hellman-group1-sha1
* host_key: ssh-rsa
* encryption_server: aes128-cbc
* encryption_client: aes128-cbc
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client:
* language_server:
D, [2017-07-17T12:19:38.453105 #61274] DEBUG -- net.ssh.transport.algorithms[3f9ed39d9868]: exchanging keys
D, [2017-07-17T12:19:38.455316 #61274] DEBUG -- socket[3f9ecf7cc77c]: queueing packet nr 1 type 30 len 140
D, [2017-07-17T12:19:38.455363 #61274] DEBUG -- socket[3f9ecf7cc77c]: sent 144 bytes
D, [2017-07-17T12:19:38.817327 #61274] DEBUG -- socket[3f9ecf7cc77c]: read 704 bytes
D, [2017-07-17T12:19:38.817499 #61274] DEBUG -- socket[3f9ecf7cc77c]: received packet nr 1 type 31 len 700
D, [2017-07-17T12:19:38.818445 #61274] DEBUG -- socket[3f9ecf7cc77c]: queueing packet nr 2 type 21 len 20
D, [2017-07-17T12:19:38.818516 #61274] DEBUG -- socket[3f9ecf7cc77c]: sent 24 bytes
D, [2017-07-17T12:19:38.826061 #61274] DEBUG -- socket[3f9ecf7cc77c]: read 16 bytes
D, [2017-07-17T12:19:38.826125 #61274] DEBUG -- socket[3f9ecf7cc77c]: received packet nr 2 type 21 len 12
D, [2017-07-17T12:19:38.826551 #61274] DEBUG -- net.ssh.authentication.session[3f9ecf581300]: beginning authentication of `user'
D, [2017-07-17T12:19:38.826727 #61274] DEBUG -- socket[3f9ecf7cc77c]: queueing packet nr 3 type 5 len 28
D, [2017-07-17T12:19:38.826788 #61274] DEBUG -- socket[3f9ecf7cc77c]: sent 52 bytes
D, [2017-07-17T12:19:38.834529 #61274] DEBUG -- socket[3f9ecf7cc77c]: read 52 bytes
D, [2017-07-17T12:19:38.834611 #61274] DEBUG -- socket[3f9ecf7cc77c]: received packet nr 3 type 6 len 28
D, [2017-07-17T12:19:38.834850 #61274] DEBUG -- net.ssh.authentication.session[3f9ecf581300]: trying none
D, [2017-07-17T12:19:38.834976 #61274] DEBUG -- socket[3f9ecf7cc77c]: queueing packet nr 4 type 50 len 44
D, [2017-07-17T12:19:38.835034 #61274] DEBUG -- socket[3f9ecf7cc77c]: sent 68 bytes
D, [2017-07-17T12:19:38.860495 #61274] DEBUG -- socket[3f9ecf7cc77c]: read 52 bytes
D, [2017-07-17T12:19:38.860590 #61274] DEBUG -- socket[3f9ecf7cc77c]: received packet nr 4 type 51 len 28
D, [2017-07-17T12:19:38.860710 #61274] DEBUG -- net.ssh.authentication.session[3f9ecf581300]: allowed methods: password
D, [2017-07-17T12:19:38.860776 #61274] DEBUG -- net.ssh.authentication.methods.none[3f9ed3d1acc0]: none failed
D, [2017-07-17T12:19:38.860872 #61274] DEBUG -- net.ssh.authentication.session[3f9ecf581300]: trying password
D, [2017-07-17T12:19:38.861000 #61274] DEBUG -- socket[3f9ecf7cc77c]: queueing packet nr 5 type 50 len 60
D, [2017-07-17T12:19:38.861055 #61274] DEBUG -- socket[3f9ecf7cc77c]: sent 84 bytes
D, [2017-07-17T12:19:38.999199 #61274] DEBUG -- socket[3f9ecf7cc77c]: read 68 bytes
D, [2017-07-17T12:19:38.999391 #61274] DEBUG -- socket[3f9ecf7cc77c]: received packet nr 5 type 53 len 44
I, [2017-07-17T12:19:38.999485 #61274]  INFO -- net.ssh.authentication.session[3f9ecf581300]: Password incorrect.


D, [2017-07-17T12:19:39.050181 #61274] DEBUG -- socket[3f9ecf7cc77c]: read 52 bytes
D, [2017-07-17T12:19:39.050312 #61274] DEBUG -- socket[3f9ecf7cc77c]: received packet nr 6 type 51 len 28
D, [2017-07-17T12:19:39.050383 #61274] DEBUG -- net.ssh.authentication.session[3f9ecf581300]: allowed methods: password
D, [2017-07-17T12:19:39.050471 #61274] DEBUG -- net.ssh.authentication.methods.password[3f9ed3d21d40]: password failed
E, [2017-07-17T12:19:39.050533 #61274] ERROR -- net.ssh.authentication.session[3f9ecf581300]: all authorization methods failed (tried none, password)
IOError: closed stream
from .bundle/ruby/2.2.0/gems/net-ssh-4.2.0.rc1/lib/net/ssh/transport/session.rb:128:in `close'
```
Sadly I don't get a more detailed stacktrace.

**Comment by tfluehmann** [comment]
Maybe we could add here: https://github.com/net-ssh/net-ssh/blob/v4.2.0.rc1/lib/net/ssh/transport/session.rb#L128

```ruby 
socket.close rescue nil
```

Would probably fix the error and give the original error (authentication failure).

**Comment by mfazekas** [comment]
Hm i still could not reproduce, i've tried `sdf.org` as server:

```ruby
gem 'net-ssh', '= 4.2.0.rc1'
require 'net/ssh'
puts Net::SSH::Version::CURRENT

Net::SSH.start('sdf.org', "user", password: 'wrong', non_interactive: true, auth_methods: ['none', 'password'], verbose: :debug)
```

```
...
E, [2017-07-17T12:59:03.583899 #19501] ERROR -- net.ssh.authentication.session[3ff49a44f6c8]: all authorization methods failed (tried none, password)
/Users/boga/.rvm/gems/ruby-2.4.0/gems/net-ssh-4.2.0.rc1/lib/net/ssh.rb:254:in `start': Authentication failed for user user@sdf.org (Net::SSH::AuthenticationFailed)
	from ./tryout/test_ioerror_536.rb:5:in `<main>'
```

**Comment by tfluehmann** [comment]
For me it becomes a bit weird too, I am trying to connect to Juniper, Huawei and Cisco Network devices and I can just reproduce the behaviour with them. I set up a docker container with an ssh daemon and I got the same result as you did:

```ruby
irb(main):005:0> Net::SSH.start("1a5e9e4d5d4b", "root", password: "test", non_interactive: true)
Net::SSH::AuthenticationFailed: Authentication failed for user root@1a5e9e4d5d4b
	from /usr/local/bundle/gems/net-ssh-4.2.0.rc1/lib/net/ssh.rb:254:in `start'
	from (irb):5
	from /usr/local/bin/irb:11:in `<main>'
irb(main):006:0>
```

But as I said before, why not add the rescue nil, probably it's the case because the machine immediately closes the connection and cannot finish the close on the socket.

**Comment by mfazekas** [comment]
Because i'd like to understand what's going on. We don't want `rescue nil` we might add rescue + check if it's a closed exception, but i'd really love to see the issue reproduced so we understand the root cause. As you noted some behaviour new in 4.2 caused the issue, i'd like to understand which and why. 

My candidate would be this:
https://github.com/net-ssh/net-ssh/commit/6572c5f54ee53df08ae47684a11a0ae9885a64de

**Comment by tfluehmann** [comment]
Yeah would be cool to find the issue true. To be honest this would be my candiate too.
Until now I could just reproduce this issue with netelements, in my local docker environment it's all working fine. I'll investigate further.

**Comment by mfazekas** [comment]
Looks i can reproduce the issue with ruby 2.2.0 but not with ruby 2.4.0

**Comment by mfazekas** [comment]
Seems to be caused by #529

in particular by this line:
https://github.com/net-ssh/net-ssh/pull/529/files#diff-363d75065e16799ade2a963fdfb7f75bR253

**Comment by amontalban** [comment]
Hey guys,

I had this issue today when using `kitchen destroy`:

```
[kitchen test mysql-server] /home/jenkins-slave/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/transport/session.rb:128:in `close': closed stream (IOError)
[kitchen test mysql-server] 	from /home/jenkins-slave/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/transport/session.rb:128:in `close'
[kitchen test mysql-server] 	from /home/jenkins-slave/.rvm/gems/ruby-2.2.5/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:128:in `close'
[kitchen test mysql-server] 	from /home/jenkins-slave/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.15.0/lib/kitchen/transport/ssh.rb:115:in `close'
[kitchen test mysql-server] 	from /home/jenkins-slave/.rvm/gems/ruby-2.2.5/bundler/gems/kitchen-sync-83d7e1fbe24a/lib/kitchen/transport/sftp.rb:73:in `close'
[kitchen test mysql-server] 	from /home/jenkins-slave/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.15.0/lib/kitchen/transport/ssh.rb:98:in `cleanup!'
[kitchen test mysql-server] 	from /home/jenkins-slave/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:285:in `cleanup!'
[kitchen test mysql-server] 	from /home/jenkins-slave/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:205:in `run_action_in_thread'
[kitchen test mysql-server] 	from /home/jenkins-slave/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
```

Upgrading to Ruby 2.4.1 fixed the problem for me so thanks for the workaround!

**Comment by tfluehmann** [comment]
Works perfectly fine with 4.0.2.rc2 👍 💯
