### ISSUE TITLE
require fails with 5.0.0beta1 (uninitialized SimpleDelegator)

### ISSUE THREAD

**Issue by Try2Code** [net-ssh/net-ssh#572]
### Expected behavior

I just want to start a connection using the ``start`` method (see #571)

### Actual behavior

revision 6879d5d
require 'net/ssh' fails

### System configuration

- net-ssh 5.0.0beta1
- Ruby 2.5.0

### Example Error

```ruby

>> require 'net/ssh'
Traceback (most recent call last):
       16: from /usr/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
       15: from /usr/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
       14: from /home/ram/.gem/ruby/2.5.0/gems/net-ssh-5.0.0.beta1/lib/net/ssh.rb:11:in `<top (required)>'
       13: from /usr/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
       12: from /usr/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
       11: from /home/ram/.gem/ruby/2.5.0/gems/net-ssh-5.0.0.beta1/lib/net/ssh/transport/session.rb:6:in `<top (required)>'
       10: from /usr/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        9: from /usr/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        8: from /home/ram/.gem/ruby/2.5.0/gems/net-ssh-5.0.0.beta1/lib/net/ssh/transport/algorithms.rb:4:in `<top (required)>'
        7: from /usr/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        6: from /usr/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        5: from /home/ram/.gem/ruby/2.5.0/gems/net-ssh-5.0.0.beta1/lib/net/ssh/transport/cipher_factory.rb:2:in `<top (required)>'
        4: from /usr/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        3: from /usr/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        2: from /home/ram/.gem/ruby/2.5.0/gems/net-ssh-5.0.0.beta1/lib/net/ssh/transport/ctr.rb:3:in `<top (required)>'
        1: from /home/ram/.gem/ruby/2.5.0/gems/net-ssh-5.0.0.beta1/lib/net/ssh/transport/ctr.rb:5:in `<module:Transport>'
NameError (uninitialized constant Net::SSH::Transport::SimpleDelegator)
>> puts Net::SSH::Version::CURRENT
5.0.0.beta1
=> nil
>> 
>> @host = 'localhost'
=> "localhost"
>> @user = ENV['USER']
=> "ram"
>> Net::SSH.start(@host, @user) do |ssh|
?>   puts ssh.exec!('echo "hello"')
>> end
Traceback (most recent call last):
        2: from /bin/irb:11:in `<main>'
        1: from (irb):6
NoMethodError (undefined method `start' for Net::SSH:Module)
```

**Comment by Try2Code** [comment]
using arch linux, openssl 1.1.0g
