### ISSUE TITLE
Kex exception thrown connecting to Windows OpenSSH

### ISSUE THREAD

**Issue by joewstroman** [net-ssh/net-ssh#592]
**Expected behavior:**
Connect to Windows OpenSSH server

**Actual behavior:**
Throws kex exception, but using other ssh implementations work as expected.

**System configuration:**
- net-ssh: 4.2.0
- Ruby: 2.5.0 or 2.3.0

**Script:**
```ruby
gem 'net-ssh', '= 4.2.0'
require 'net/ssh'
puts Net::SSH::Version::CURRENT

Net::SSH::start('windows-server')
```
**Stacktrace:**
```
/usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/algorithms.rb:345:in `negotiate': could not settle on kex algorithm (Net::SSH::Exception)
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/algorithms.rb:319:in `negotiate_algorithms'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/algorithms.rb:200:in `proceed!'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/algorithms.rb:149:in `accept_kexinit'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:88:in `initialize'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
```

**Comment by joewstroman** [comment]
Ah it works if you install from source

https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH
