### ISSUE TITLE
Net SSH fails with ECDSA keys without private key file

### ISSUE THREAD

**Issue by agrare** [net-ssh/net-ssh#619]
### Expected behavior

With a private key (e.g. `.ssh/id_rsa`) and no public key (e.d. `.ssh/id_rsa.pub`) net-ssh typically derives the public key from the private key [ref](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/key_manager.rb#L233).  This works great for RSA type ssh keys but not for ECDSA type ssh keys.

### Actual behavior

With a private key of type `OpenSSL::PKey::EC`, calling `.public_key` returns a `OpenSSL::PKey::EC::Point` object.  When this is being written out to the `Net::SSH::Buffer` `.to_blob` is called on the key [ref](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/buffer.rb#L393).

The `.to_blob` method is defined for `OpenSSL::PKey::EC` [ref](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/openssl.rb#L184-L189) but not for `OpenSSL::PKey::EC::Point` which leads to the following error:
```
Traceback (most recent call last):
       16: from (irb):2
       15: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh.rb:246:in `start'
       14: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:71:in `authenticate'
       13: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:71:in `each'
       12: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
       11: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
       10: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
        9: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:119:in `each'
        8: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
        7: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
        6: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:51:in `authenticate_with'
        5: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:41:in `send_request'
        4: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:32:in `build_request'
        3: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/buffer.rb:393:in `write_key'
        2: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/buffer.rb:393:in `each'
        1: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/buffer.rb:393:in `block in write_key'
NoMethodError (undefined method `to_blob' for #<OpenSSL::PKey::EC::Point:0x000055bc8dc87ce8>)
Did you mean?  to_bn
```

### System configuration

- net-ssh version
```ruby
irb(main):004:0> puts Net::SSH::Version::CURRENT
5.0.2
```

- Ruby version
```
ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

- System type
`Debian sid`

### Example App

```
root@net-ssh-test:~# ssh-keygen -t ecdsa
Generating public/private ecdsa key pair.
Enter file in which to save the key (/root/.ssh/id_ecdsa): 
Created directory '/root/.ssh'.
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /root/.ssh/id_ecdsa.
Your public key has been saved in /root/.ssh/id_ecdsa.pub.
root@net-ssh-test:~# irb
irb(main):001:0> require 'net/ssh'
=> true
irb(main):002:0> Net::SSH.start(host, user, :password => password) { |ssh| ssh.exec("echo 'hello world'") }; nil
=> nil
irb(main):003:0> 
root@net-ssh-test:~# rm .ssh/id_ecdsa.pub 
root@net-ssh-test:~# irb
irb(main):001:0> require 'net/ssh'
=> true
irb(main):002:0> Net::SSH.start(host, user, :password => password) { |ssh| ssh.exec("echo 'hello world'") }; nil
Traceback (most recent call last):
       16: from (irb):2
       15: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh.rb:246:in `start'
       14: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:71:in `authenticate'
       13: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:71:in `each'
       12: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
       11: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
       10: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
        9: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:119:in `each'
        8: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
        7: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
        6: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:51:in `authenticate_with'
        5: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:41:in `send_request'
        4: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:32:in `build_request'
        3: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/buffer.rb:393:in `write_key'
        2: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/buffer.rb:393:in `each'
        1: from /var/lib/gems/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/buffer.rb:393:in `block in write_key'
NoMethodError (undefined method `to_blob' for #<OpenSSL::PKey::EC::Point:0x000055bc8dc87ce8>)
Did you mean?  to_bn
```

**Comment by Fryguy** [comment]
Note that this happens even if you're using password authentication, which was unexpected, since the key_manager is initialized regardless.  Passing `:auth_methods => ['password']` does workaround the issue.
