### ISSUE TITLE
Bad file handle - ruby bug 3

### ISSUE THREAD

**Issue by TLINDEN** [net-ssh/net-ssh#626]
I maintain a scraper which logs into several hundred cloud servers via ssh regularly, which calls puppet facter and other commands, parses their output and puts the results into a database. The system works well from the development environment, but it dies from the production environment (targets are the same though).

In order to reproduce I created a small script with minimal code, see below

### Expected behavior

Script shall run til the end.

### Actual behavior

After some 30-90 ssh connections (random) the module receives an EBADF  (bad file descriptor) from the kernel and gets killed with SIG 9.

### System configuration

- net-ssh version rubygem-net-ssh-5.0.2,2
- Ruby version ruby-2.3.5,1

OS: FreeBSD Jail.

### Example App

Please provide an example script that reproduces the problem. This will save maintainers time so they can spend it fixing your issues instead of trying to build a reproduction case from sparse instructions.

You can use this as stating point:

```ruby
#!/usr/local/bin/ruby

require 'rubygems'
require 'net/ssh'

servers = %w{lots of servers}
options = {:timeout => 5, :verify_host_key => :never}
command = ARGV.shift

def exec(session, command)
  puts "  Executing #{command}"
  lines = session.exec!(command)
  puts "    - #{lines}"
end

if command then
  servers.each do |server|
    begin
      puts "Connecting to #{server}"
      ssh = Net::SSH.start(server, 'root', options)
      exec(ssh, command)
    rescue StandardError => e
      printf("Ignoring failure:  %s\n", e.message)
    end
  end
end
```

Output after a couple dozen loops:
```
Ignoring failure:  
Connecting to $server
  Executing date
[ASYNC BUG] (3)
EBADF

ruby 2.3.5p376 (2017-09-14 revision 59905) [amd64-freebsd10]

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html
```

If I try catch the error, I get:
```
Ignoring failure:  
/usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/transport/state.rb:81:in `update': OpenSSL::Cipher::CipherError
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/transport/state.rb:81:in `update_cipher'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/transport/packet_stream.rb:155:in `enqueue_packet'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/transport/session.rb:247:in `enqueue_message'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:444:in `send_message'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/channel.rb:492:in `send_channel_request'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/channel.rb:162:in `exec'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:381:in `block in exec'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/channel.rb:533:in `do_open_confirmation'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:644:in `channel_open_confirmation'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:549:in `dispatch_incoming_packets'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:249:in `ev_preprocess'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/event_loop.rb:101:in `each'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/event_loop.rb:101:in `ev_preprocess'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/event_loop.rb:29:in `process'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:228:in `process'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:181:in `block in loop'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:181:in `loop'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:181:in `loop'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/channel.rb:272:in `wait'
        from /usr/local/lib/ruby/gems/2.3/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:428:in `exec!'
        from ./test.rb:14:in `exec'
        from ./test.rb:34:in `block in <main>'
        from ./test.rb:30:in `each'
        from ./test.rb:30:in `<main>'
```

It has nothing to do with openssl though, it just happens to reach the point where the "ruby bug" seems to fire are this point - I think.

Do you have any idea how to fix/circumvent/nail down this?

Thanks,
Tom

**Comment by mfazekas** [comment]
@TLINDEN thanks for the report, sounds scary, i don not have any idea on how to debug/troubleshoot this. (strace/dtrace might or might not help). Is it possible we ran out of file descriptiors?

**Comment by TLINDEN** [comment]
> Is it possible we ran out of file descriptiors?

Since this is a jail, this is what I suspect as well. But on the other hand, there are a couple dozen open sessions, which is far away from any limit.

I googled the ruby error message and found some hits in relation to threads. As far as I know, you use threads for the i/o channels, may it be possible that there are too many threads? Would it be possible to count them somehow?

**Comment by mfazekas** [comment]
@TLINDEN  i don't think there are too many threads. You should be able to see the threads with `ps` the file descriptiors with `/proc/<pid>/fd` or `procstat`? on freebsd.

**Comment by TLINDEN** [comment]
yes, only two:
```
  PID    TID COMM             TDNAME           KSTACK                       
81307 101721 ruby             ruby-timer-thr   mi_switch sleepq_catch_signals sleepq_wait_sig _cv_wait_sig seltdwait kern_poll sys_poll amd64_syscall Xfast_syscall 
81307 103141 ruby             -                mi_switch sleepq_catch_signals sleepq_timedwait_sig _cv_timedwait_sig_sbt seltdwait kern_select sys_select amd64_syscall Xfast_syscall 
```

**Comment by mfazekas** [comment]
@TLINDEN i'm closing this please comment if you have new info that might help to solve it
