### ISSUE TITLE
ED25519 keys with passphrase throw ArgumentError

### ISSUE THREAD

**Issue by kke** [net-ssh/net-ssh#658]
### Expected behavior

Using an ed25519 ssh key with a passphrase, It should prompt for passphrase like the other type of keys when `non_interactive` is `false`. 

```
> Net::SSH.start('host', 'user', keys: [File.join(Dir.home, '.ssh/id_rsa')])
Enter passphrase for ~/.ssh/id_rsa:
```

### Actual behavior

```
ArgumentError : Decrypt failed on private key
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/ed25519.rb:77:in `read'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/key_factory.rb:114:in `block in classify_key'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/key_factory.rb:61:in `load_data_private_key'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/key_factory.rb:44:in `load_private_key'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/session.rb:71:in `each'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh/authentication/session.rb:71:in `authenticate'
~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/net-ssh-5.1.0/lib/net/ssh.rb:246:in `start'
```

With `ssh-agent` it works fine.

### System configuration

- `5.1`
- `2.6`

### Example App

```ruby
gem 'net-ssh', '= 5.1.0'
require 'net/ssh'
user = ENV['USER']

# Generate a key with passphrase:
system('ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/id_ed25519 -P "foo"')

Net::SSH.start('127.0.0.1', user keys: [File.join(Dir.home, '.ssh/id_ed25519')])
```

**Comment by mfazekas** [comment]
@kke thanks for the bugreport i was able to reproduce it. 
Strange as we have test for pwd protected ed25519 keys and for that particular example it works fine, but not for keys generated by `OpenSSH_7.8p1, LibreSSL 2.7.3` (what i've tested)

https://github.com/net-ssh/net-ssh/blob/master/test/authentication/test_ed25519.rb#L31-L50
