### ISSUE TITLE
misleading error message when private rsa key is password protected

### ISSUE THREAD

**Issue by kzw** [net-ssh/net-ssh#674]
### Expected behavior

It should prompt password to decrypt ssh rsa private key or emit other generic error.
### Actual behavior

Wrong error output

```
>>>>>>     Failed to complete #converge action: [OpenSSH keys only supported if ED25519 is available

net-ssh requires the following gems for ed25519 support:
 * rbnacl (>= 3.2, < 5.0)
 * rbnacl-libsodium, if your system doesn't have libsodium installed.
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/478 for more information
Gem::MissingSpecError : "Could not find 'rbnacl' (< 5.0, >= 3.2.0) among 251 total gem(s)

```

### System configuration

- net-ssh 4.1.0
- Ruby  2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]

### Example App

```
$ ssh-add -D
$ ruby
require 'net/ssh'
puts Net::SSH::Version::CURRENT

@host = 'localhost'
@user = ENV['USER']
Net::SSH.start(@host, @user) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```

**Comment by mfazekas** [comment]
@kzw Please try and rereport with latest version, if the issue still persists (5.*)

**Comment by kzw** [comment]
Tried with 5.2.0 

```
5.2.0
Enter passphrase for key '/Users/me/.ssh/id_rsa': 
/Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/ed25519_loader.rb:21:in `raiseUnlessLoaded': OpenSSH keys only supported if ED25519 is available (NotImplementedError)
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
Gem::LoadError : "Could not find 'ed25519' (~> 1.2) among 17 total gem(s)
Checked in 'GEM_PATH=/Users/me/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information"
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:202:in `classify_key'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:53:in `load_data_private_key'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:44:in `load_private_key'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `authenticate'
	from /Library/Ruby/Gems/2.3.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:250:in `start'
	from a.rb:6:in `<main>'

```


For the exact same ssh config there is no error if private key isn't password protected.

```
$ ruby --version 
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```

**Comment by mfazekas** [comment]
@kzw can you try installing the gems mentioned? As the message writes `OpenSSH keys only supported if ED25519 is available`. Maybe i should clarify this, and we could write `new style OpenSSH keys only supported if ...`

**Comment by kzw** [comment]
I can confirm that after installing those gems I get no error.  But it makes no sense to give me no error when the same key is not password protected.  The same open ssh key is supported without the gems, no?  Is password protecting the key somehow change the key *style*?

**Comment by mfazekas** [comment]
@kzw yep, when the key is password protected it uses `bcrypt_pbkdf` alg for encryption.

https://flak.tedunangst.com/post/new-openssh-key-format-and-bcrypt-pbkdf

it's possible that `bcrypt_pbkdf` would be enough and ed25519, is not neccesary.

**Comment by kzw** [comment]
No.  without ed25519 it does not work.  

Also, it is asking for password twice for some reason; it's probably a feature or a bug.  I experienced it the first time and I thought I typed it wrong the first time but it always ask for password twice.
