### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by jnaklaas** [net-ssh/net-ssh#715]
** Summary **
I'm using rubygem capistrano to deploy my websites.  The setup that has always been working for me, fails on a clean installed mac. Not sure why, but I end up with an error `undefined method `[]' for nil:NilClass` apparently thrown by net-ssh (which is used by capistrano/sshkit).

```sh
Caused by:
NoMethodError: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/ed25519.rb:79:in `read'
```
Full stacktrace below.

** Steps to reproduce **
On a clean installed mac, I installed ruby and capistrano trying to get my web projects to deploy with capistrano the way they've been working previously.

Error is thrown when using capistrano command `cap production deploy:check`. Output using `--trace`:
```sh
$ cap production deploy:check --trace
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke deploy:check (first_time)
** Invoke git:check (first_time)
** Invoke git:wrapper (first_time)
** Execute git:wrapper
00:00 git:wrapper
      01 mkdir -p /tmp
Enter passphrase for ~/.ssh/id_rsa:
#<Thread:0x00007fa4feaaaf50@~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:10 run> terminated with excep
tion (report_on_exception is true):
Traceback (most recent call last):
        1: from ~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception
while executing as user@ssh.domain.tld: undefined method `[]' for nil:NilClass (SSHKit::Runner::ExecuteError)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@ssh.domain.tld: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'

Caused by:
NoMethodError: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/ed25519.rb:79:in `read'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:127:in `read'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:61:in `load_data_private_key'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:44:in `load_private_key'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `each'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh.rb:250:in `start'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/connection_pool.rb:63:in `call'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/connection_pool.rb:63:in `with'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/netssh.rb:177:in `with_ssh'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/netssh.rb:130:in `execute_command'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `tap'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:80:in `execute'
~/.rvm/gems/ruby-2.5.6/gems/capistrano-3.11.1/lib/capistrano/scm/tasks/git.rake:8:in `block (3 levels) in eval_rakefile'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `run'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => deploy:check => git:check => git:wrapper
```
My setup:
```
Environment

    Ruby     ruby 2.5.6p201 (2019-08-28 revision 67796) [x86_64-darwin18]
    Rubygems 3.0.6
    Bundler  1.17.3

Gems

    capistrano          3.11.1
    airbrussh           1.3.4
    rake                12.3.3
    sshkit              1.20.0
    net-ssh             5.2.0
    capistrano-composer 0.0.6
    capistrano-npm      1.0.3
    capistrano-wpcli    0.1.4
```
Full list of local installed gems
```sh
airbrussh (1.3.4, 1.3.2)
bcrypt_pbkdf (1.0.1)
bigdecimal (default: 1.3.4)
bundler (default: 1.17.3)
bundler-unload (1.0.2)
capistrano (3.11.0, 3.10.2, 3.2.1)
capistrano-composer (0.0.6, 0.0.4)
capistrano-npm (1.0.3)
capistrano-wpcli (0.1.4, 0.0.9)
cmath (default: 1.0.0)
colorize (0.7.3)
concurrent-ruby (1.1.5)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
ed25519 (1.2.4)
etc (default: 1.0.0)
executable-hooks (1.6.0)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
gdbm (default: 2.0.0)
gem-wrappers (1.4.0)
i18n (1.6.0, 0.6.9)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (default: 2.1.0)
minitest (5.10.3)
net-scp (2.0.0, 1.2.1)
net-ssh (5.2.0, 2.9.1)
net-telnet (0.1.1)
openssl (default: 2.1.2)
power_assert (1.1.1)
psych (default: 3.0.2)
rake (12.3.3, 12.3.2, 12.3.0, 10.3.2)
rdoc (default: 6.0.1.1)
rubygems-bundler (1.4.5)
rvm (1.11.3.9)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
sshkit (1.20.0, 1.19.1, 1.17.0, 1.5.1)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
test-unit (3.2.7)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```

**Comment by fwininger** [comment]
I'm perplex, it's seems you would like to use RSA key but you have an exception from the ed25519 code.

Can you give us the header of your `~/.ssh/id_rsa` file (only the header, dont copy the full private key) ?

It's :

```
-----BEGIN OPENSSH PRIVATE KEY-----
```

or

```
-----BEGIN RSA PRIVATE KEY-----
```

**Comment by jnaklaas** [comment]
`-----BEGIN OPENSSH PRIVATE KEY-----`

You're right about where things went wrong. I regenerated the RSA keys and posted the new public key to the server, did some testing, everything is working now.
