### ISSUE TITLE
SOCKS5 issue: uninitialized constant Net::SSH::ProxyError (NameError)

### ISSUE THREAD

**Issue by gordonrs** [net-ssh/net-ssh#718]
### Expected behavior

Expected the proxy to be initialized with the values provided.

### Actual behavior

Throws an exception saying there is a name error.

### System configuration

- net-ssh version 5.2
- Ruby version 2.6

### Example App

```ruby
def test_ssh(ip_str, port)
  begin
    proxy = Net::SSH::Proxy::SOCKS5.new('127.0.0.1', 10500)
    Net::SSH.start(:host => ip_str,
                   :port => port,
                   :user => 'CENSORED',
                   :password => 'CENSORED',
                   :verify_host_key => false,
                   :proxy => proxy,
                   :user_known_hosts_file => %w(~/src/projectname/known_hosts)) do |ssh|
      status(ip_str, 'Connected')
    end
  rescue Net::SSH::AuthenticationFailed
    status(ip_str, 'AuthenticationFailed')
  rescue Net::SSH::ProxyError
    status(ip_str, 'ProxyError')
  rescue Net::SSH::Authentication::DisallowedMethod
    status(ip_str, 'DisallowedMethod')
  rescue Net::SSH::ConnectionTimeout
    status(ip_str, 'ConnectionTimeout')
  rescue Net::SSH::Disconnect
    status(ip_str, 'Disconnect')
  rescue Net::SSH::HostKeyError
    status(ip_str, 'HostKeyError')
  rescue Net::SSH::ChannelRequestFailed
    status(ip_str, 'ChannelRequestFailed')
  rescue Net::SSH::ChannelOpenFailed
    status(ip_str, 'ChannelOpenFailed')
  rescue Net::SSH::Authentication::KeyManagerError
    status(ip_str, 'KeyManagerError')
  rescue Net::SSH::Authentication::AgentError
    status(ip_str, 'AgentError')
  end
end
```
Followed the documentation example here: https://www.rubydoc.info/github/net-ssh/net-ssh/Net/SSH/Proxy/SOCKS5

**Comment by gordonrs** [comment]
```
Traceback (most recent call last):
        16: from ./CENSOREDFILE.rb:219:in `<main>'
        15: from ./CENSOREDFILE.rb:215:in `parse'
        14: from /usr/lib/ruby/2.6.0/optparse.rb:1678:in `parse!'
        13: from /usr/lib/ruby/2.6.0/optparse.rb:1656:in `permute!'
        12: from /usr/lib/ruby/2.6.0/optparse.rb:1562:in `order!'
        11: from /usr/lib/ruby/2.6.0/optparse.rb:1568:in `parse_in_order'
        10: from /usr/lib/ruby/2.6.0/optparse.rb:1568:in `catch'
         9: from /usr/lib/ruby/2.6.0/optparse.rb:1614:in `block in parse_in_order'
         8: from ./CENSOREDFILE.rb:207:in `block (2 levels) in parse'
         7: from ./CENSOREDFILE.rb:158:in `internal_test'
         6: from ./CENSOREDFILE.rb:164:in `test_ssh'
         5: from /home/USERNAME/.gem/ruby/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `start'
         4: from /home/USERNAME/.gem/ruby/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `new'
         3: from /home/USERNAME/.gem/ruby/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:73:in `initialize'
         2: from /usr/lib/ruby/2.6.0/socket.rb:631:in `tcp'
         1: from /usr/lib/ruby/2.6.0/socket.rb:227:in `foreach'
/usr/lib/ruby/2.6.0/socket.rb:227:in `getaddrinfo': no implicit conversion of Hash into String (TypeError)
        11: from ./CENSOREDFILE.rb:219:in `<main>'
        10: from ./CENSOREDFILE.rb:215:in `parse'
         9: from /usr/lib/ruby/2.6.0/optparse.rb:1678:in `parse!'
         8: from /usr/lib/ruby/2.6.0/optparse.rb:1656:in `permute!'
         7: from /usr/lib/ruby/2.6.0/optparse.rb:1562:in `order!'
         6: from /usr/lib/ruby/2.6.0/optparse.rb:1568:in `parse_in_order'
         5: from /usr/lib/ruby/2.6.0/optparse.rb:1568:in `catch'
         4: from /usr/lib/ruby/2.6.0/optparse.rb:1614:in `block in parse_in_order'
         3: from ./CENSOREDFILE.rb:207:in `block (2 levels) in parse'
         2: from ./CENSOREDFILE.rb:158:in `internal_test'
         1: from ./CENSOREDFILE.rb:161:in `test_ssh'
./CENSOREDFILE.rb:175:in `rescue in test_ssh': uninitialized constant Net::SSH::ProxyError (NameError)
```

**Comment by gordonrs** [comment]
Sorry, its `Net::SSH::Proxy::Error`, my bad.
