### ISSUE TITLE
The router Nokia does not send data

### ISSUE THREAD

**Issue by Froz10** [net-ssh/net-ssh#818]
### Expected behavior

When connecting via SSH to the Nokia router, need to send data after executing the 'exec' command

### Actual behavior

When connecting via SSH to the Nokia router, no data is sent from the server, but the same script works fine with Cisco and Huawei

### System configuration

- net-ssh version - 6.1.0
- Ruby version - 2.7.2

### Example App

You can use this as stating point:

```ruby
Net::SSH.start(host, user, password: password, verbose: :debug) do |ssh|
  ssh.open_channel do |ch|
    ch.exec "command"
    ch.on_data do |ch, data|
      puts data
    end
  end
  
  ssh.loop  
end
```
D, [2021-06-15T17:49:06.678260 #696] DEBUG -- net.ssh.transport.session[21c]: establishing connection to XX.XX.XX.XX
D, [2021-06-15T17:49:06.792084 #696] DEBUG -- net.ssh.transport.session[21c]: connection established
I, [2021-06-15T17:49:06.792248 #696]  INFO -- net.ssh.transport.server_version[230]: negotiating protocol version
D, [2021-06-15T17:49:06.792353 #696] DEBUG -- net.ssh.transport.server_version[230]: local is `SSH-2.0-Ruby/Net::SSH_6.1.0 x86_64-linux'
D, [2021-06-15T17:49:06.911926 #696] DEBUG -- net.ssh.transport.server_version[230]: remote is `SSH-2.0-OpenSSH_3.5p1'
I, [2021-06-15T17:49:06.912687 #696]  INFO -- net.ssh.transport.algorithms[244]: sending KEXINIT
D, [2021-06-15T17:49:06.912965 #696] DEBUG -- socket[258]: queueing packet nr 0 type 20 len 748
D, [2021-06-15T17:49:06.913059 #696] DEBUG -- socket[258]: sent 752 bytes
D, [2021-06-15T17:49:07.024941 #696] DEBUG -- socket[258]: read 624 bytes
D, [2021-06-15T17:49:07.025069 #696] DEBUG -- socket[258]: received packet nr 0 type 20 len 620
I, [2021-06-15T17:49:07.025156 #696]  INFO -- net.ssh.transport.algorithms[244]: got KEXINIT from server
I, [2021-06-15T17:49:07.025234 #696]  INFO -- net.ssh.transport.algorithms[244]: negotiating algorithms
D, [2021-06-15T17:49:07.025470 #696] DEBUG -- net.ssh.transport.algorithms[244]: negotiated:
* kex: diffie-hellman-group14-sha1
* host_key: ssh-rsa
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client:
* language_server:
D, [2021-06-15T17:49:07.025549 #696] DEBUG -- net.ssh.transport.algorithms[244]: exchanging keys
D, [2021-06-15T17:49:07.030351 #696] DEBUG -- socket[258]: queueing packet nr 1 type 30 len 268
D, [2021-06-15T17:49:07.030449 #696] DEBUG -- socket[258]: sent 272 bytes
D, [2021-06-15T17:49:07.618991 #696] DEBUG -- socket[258]: read 592 bytes
D, [2021-06-15T17:49:07.619139 #696] DEBUG -- socket[258]: received packet nr 1 type 31 len 572
D, [2021-06-15T17:49:07.620292 #696] DEBUG -- socket[258]: queueing packet nr 2 type 21 len 20
D, [2021-06-15T17:49:07.620413 #696] DEBUG -- socket[258]: sent 24 bytes
D, [2021-06-15T17:49:07.620591 #696] DEBUG -- socket[258]: received packet nr 2 type 21 len 12
D, [2021-06-15T17:49:07.621034 #696] DEBUG -- net.ssh.authentication.session[26c]: beginning authentication of `xxxxxxxx'
D, [2021-06-15T17:49:07.621235 #696] DEBUG -- socket[258]: queueing packet nr 3 type 5 len 28
D, [2021-06-15T17:49:07.621316 #696] DEBUG -- socket[258]: sent 52 bytes
D, [2021-06-15T17:49:07.849834 #696] DEBUG -- socket[258]: read 52 bytes
D, [2021-06-15T17:49:07.850030 #696] DEBUG -- socket[258]: received packet nr 3 type 6 len 28
D, [2021-06-15T17:49:07.850340 #696] DEBUG -- net.ssh.authentication.session[26c]: trying none
D, [2021-06-15T17:49:07.850623 #696] DEBUG -- socket[258]: queueing packet nr 4 type 50 len 44
D, [2021-06-15T17:49:07.850732 #696] DEBUG -- socket[258]: sent 68 bytes
D, [2021-06-15T17:49:07.964980 #696] DEBUG -- socket[258]: read 136 bytes
D, [2021-06-15T17:49:07.965218 #696] DEBUG -- socket[258]: received packet nr 4 type 53 len 44
I, [2021-06-15T17:49:07.965377 #696]  INFO -- net.ssh.authentication.session[26c]: ###!!!!!!!!!!!!!!!!!!!!!!!###

D, [2021-06-15T17:49:07.965659 #696] DEBUG -- socket[258]: received packet nr 5 type 51 len 44
D, [2021-06-15T17:49:07.965796 #696] DEBUG -- net.ssh.authentication.session[26c]: allowed methods: publickey,password
D, [2021-06-15T17:49:07.965885 #696] DEBUG -- net.ssh.authentication.methods.none[280]: none failed
D, [2021-06-15T17:49:07.965954 #696] DEBUG -- net.ssh.authentication.session[26c]: trying publickey
D, [2021-06-15T17:49:07.966175 #696] DEBUG -- net.ssh.authentication.agent[294]: connecting to ssh-agent
E, [2021-06-15T17:49:07.966233 #696] ERROR -- net.ssh.authentication.agent[294]: could not connect to ssh-agent: Agent not configured
D, [2021-06-15T17:49:07.966403 #696] DEBUG -- net.ssh.authentication.methods.publickey[2bc]: trying publickey (1d:c2:80:d2:a2:9e:4e:41:40:ee:66:de:c1:89:de:c4)
D, [2021-06-15T17:49:07.966576 #696] DEBUG -- socket[258]: queueing packet nr 5 type 50 len 476
D, [2021-06-15T17:49:07.966677 #696] DEBUG -- socket[258]: sent 500 bytes
D, [2021-06-15T17:49:08.080960 #696] DEBUG -- socket[258]: read 68 bytes
D, [2021-06-15T17:49:08.081158 #696] DEBUG -- socket[258]: received packet nr 6 type 51 len 44
D, [2021-06-15T17:49:08.081409 #696] DEBUG -- net.ssh.authentication.session[26c]: allowed methods: publickey,password
D, [2021-06-15T17:49:08.081597 #696] DEBUG -- net.ssh.authentication.session[26c]: trying password
D, [2021-06-15T17:49:08.081835 #696] DEBUG -- socket[258]: queueing packet nr 6 type 50 len 76
D, [2021-06-15T17:49:08.081909 #696] DEBUG -- socket[258]: sent 100 bytes
D, [2021-06-15T17:49:08.282932 #696] DEBUG -- socket[258]: read 36 bytes
D, [2021-06-15T17:49:08.283119 #696] DEBUG -- socket[258]: received packet nr 7 type 52 len 12
D, [2021-06-15T17:49:08.283394 #696] DEBUG -- net.ssh.authentication.methods.password[2d0]: password succeeded
D, [2021-06-15T17:49:08.283803 #696] DEBUG -- socket[258]: queueing packet nr 7 type 90 len 44
D, [2021-06-15T17:49:08.283984 #696] DEBUG -- socket[258]: sent 68 bytes
D, [2021-06-15T17:49:08.398961 #696] DEBUG -- socket[258]: read 52 bytes
D, [2021-06-15T17:49:08.399206 #696] DEBUG -- socket[258]: received packet nr 8 type 91 len 28
I, [2021-06-15T17:49:08.399442 #696]  INFO -- net.ssh.connection.session[2e4]: channel_open_confirmation: 0 0 0 32768
I, [2021-06-15T17:49:08.399723 #696]  INFO -- net.ssh.connection.channel[2f8]: sending channel request "env"
D, [2021-06-15T17:49:08.399901 #696] DEBUG -- socket[258]: queueing packet nr 8 type 98 len 44
I, [2021-06-15T17:49:08.400012 #696]  INFO -- net.ssh.connection.channel[2f8]: sending channel request "exec"
D, [2021-06-15T17:49:08.400142 #696] DEBUG -- socket[258]: queueing packet nr 9 type 98 len 44
D, [2021-06-15T17:49:08.400273 #696] DEBUG -- socket[258]: sent 136 bytes
D, [2021-06-15T17:49:08.514972 #696] DEBUG -- socket[258]: read 0 bytes
Traceback (most recent call last):
        17: from test.rb:10:in `<main>'
        16: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh.rb:259:in `start'
        15: from test.rb:18:in `block in <main>'
        14: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
        13: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
        12: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `block in loop'
        11: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:227:in `process'
        10: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:28:in `process'
         9: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:100:in `ev_preprocess'
         8: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:100:in `each'
         7: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:248:in `ev_preprocess'
         6: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:545:in `dispatch_incoming_packets'
         5: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
         4: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `loop'
         3: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
         2: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/transport/packet_stream.rb:90:in `next_packet'
         1: from /usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/transport/packet_stream.rb:75:in `available_for_read?'
/usr/local/rvm/gems/ruby-2.7.2/gems/net-ssh-6.1.0/lib/net/ssh/transport/packet_stream.rb:75:in `select': closed stream (IOError)

**Comment by beeforever** [comment]
I had the same problem with OneAccess box, but request_pty fixed it. Can you try?

ssh.open_channel do |channel|
  channel.request_pty do |ch, success|
      if success
        puts "pty successfully obtained"
      else
        puts "could not obtain pty"
      end
    end

    channel.exec command
    .......
    .......

**Comment by Froz10** [comment]
My work script, thx.

```ruby
Net::SSH.start(line, user, password: password, :auth_methods => ["password"]) do |ssh|
    channel = ssh.open_channel do |ch|
      ch.send_channel_request("shell") do |ch, success|
        raise "could not execute command" unless success

        # "on_data" is called when the process writes something to stdout
        ch.on_data do |c, data|
          $stdout.print data
        end

        # "on_extended_data" is called when the process writes something to stderr
        ch.on_extended_data do |c, type, data|
          $stderr.print data
        end
        ch.send_data("show card\n")
        ch.send_data("logout\n")
      end
    end
    channel.wait

    ssh.loop { false }
  end

```
