### ISSUE TITLE
Exception while executing on host carbonite: curve name mismatched (`' with `nistp256') (SSHKit::Runner::ExecuteError)

### ISSUE THREAD

**Issue by NehaPeer** [net-ssh/net-ssh#851]
Ruby version - 2.7.3
Rails version - 6.1.3.2

net-ssh (6.3.0.beta1, 6.1.0)
net-ssh-gateway (2.0.0)
net-ssh-shell (0.1.0)

While deploying code using Capistrano gem it throws below error- 

/var/home/username/.rvm/gems/ruby-2.7.3@app/gems/net-ssh-6.1.0/lib/net/ssh/transport/openssl.rb:144:in `read_keyblob': curve name mismatched (`' with `nistp256') (Net::SSH::Exception)
	1: from /var/home/username/.rvm/gems/ruby-2.7.3@appname/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/var/home/username/.rvm/gems/ruby-2.7.3@appname/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing on host carbonite: curve name mismatched (`' with `nistp256') (SSHKit::Runner::ExecuteError)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host carbonite: curve name mismatched (`' with `nistp256')

Caused by:
Net::SSH::Exception: curve name mismatched (`' with `nistp256')

Please give some suggestions.

Thank you

**Comment by popeda97** [comment]
> Ruby version - 2.7.3 Rails version - 6.1.3.2
> 
> net-ssh (6.3.0.beta1, 6.1.0) net-ssh-gateway (2.0.0) net-ssh-shell (0.1.0)
> 
> While deploying code using Capistrano gem it throws below error-
> 
> /var/home/username/.rvm/gems/ruby-2.7.3@app/gems/net-ssh-6.1.0/lib/net/ssh/transport/openssl.rb:144:in `read_keyblob': curve name mismatched (`' with `nistp256') (Net::SSH::Exception) 1: from /var/home/username/.rvm/gems/ruby-2.7.3@appname/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute' /var/home/username/.rvm/gems/ruby-2.7.3@appname/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing on host carbonite: curve name mismatched (`' with `nistp256') (SSHKit::Runner::ExecuteError) (Backtrace restricted to imported tasks) cap aborted! SSHKit::Runner::ExecuteError: Exception while executing on host carbonite: curve name mismatched (`' with `nistp256')
> 
> Caused by: Net::SSH::Exception: curve name mismatched (`' with `nistp256')
> 
> Please give some suggestions.
> 
> Thank you
