### ISSUE TITLE
can't modify frozen String: "" when ssh-agent is misconfigured

### ISSUE THREAD

**Issue by qnighy** [net-ssh/net-ssh#867]
### Expected behavior

ssh-agent is ignored or an appropriate error message is shown if it is misconfigured.

Here a misconfigured ssh-agent immediately closes the socket on connection. In my environment it happened because a tricky bridging was needed to connect the SSH client in WSL2 to an SSH agent in Windows.

### Actual behavior

It raises the "can't modify frozen String" error.

```
/home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/buffer.rb:147:in `append': can't modify frozen String: "" (FrozenError)
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:211:in `read_packet'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:221:in `send_and_wait'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:105:in `negotiate!'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:68:in `connect'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:204:in `agent'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:113:in `each_identity'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:86:in `block in authenticate'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `each'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `authenticate'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:255:in `start'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hocho-0.3.7/lib/hocho/host.rb:220:in `make_ssh_connection'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hocho-0.3.7/lib/hocho/host.rb:207:in `ssh_connection'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hocho-0.3.7/lib/hocho/drivers/ssh_base.rb:9:in `ssh'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hocho-0.3.7/lib/hocho/drivers/mitamae.rb:17:in `run'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hocho-0.3.7/lib/hocho/runner.rb:22:in `run'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hocho-0.3.7/lib/hocho/command.rb:85:in `block in apply'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hocho-0.3.7/lib/hocho/command.rb:77:in `each'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hocho-0.3.7/lib/hocho/command.rb:77:in `apply'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /home/qnighy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/hocho-0.3.7/bin/hocho:4:in `<top (required)>'
        from /home/qnighy/.rbenv/versions/3.1.2/bin/hocho:25:in `load'
        from /home/qnighy/.rbenv/versions/3.1.2/bin/hocho:25:in `<main>'
```

This is likely caused by `IO#read` returning nil and `nil.to_s` returning a frozen string in Ruby >= 2.7.

### System configuration

- net-ssh version: 6.1.0
- Ruby version: 3.1.2

### Example App

```ruby
gem 'net-ssh', '= 6.1.0'
require 'net/ssh'
puts Net::SSH::Version::CURRENT

Thread.new do
  # Minimized reproduction for misconfigured ssh-agent
  system("nc -lNU test.sock < /dev/null >/dev/null")
end

# @host = 'localhost'
@host = 'github.com'
# @user = ENV['USER']
@user = 'git'
ENV['SSH_AUTH_SOCK'] = 'test.sock'
Net::SSH.start(@host, @user, { verify_host_key: :never }) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```

**Comment by olleolleolle** [comment]
In order to try locally, I wrapped the script in a Bundler inline invocation, and made the file executable:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'net-ssh', '= 6.1.0'
  gem 'ed25519' # An error message prompted me to add the gems ed25519 and bcrypt_pbkdf
  gem 'bcrypt_pbkdf'
end

puts Net::SSH::Version::CURRENT # => 6.1.0

Thread.new do
  # Minimized reproduction for misconfigured ssh-agent
  system("nc -lNU test.sock < /dev/null >/dev/null")
end

# @host = 'localhost'
@host = 'github.com'
# @user = ENV['USER']
@user = 'git'
ENV['SSH_AUTH_SOCK'] = 'test.sock'
Net::SSH.start(@host, @user, { verify_host_key: :never }) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```

Current output on a macOS: (`Darwin Olles-MacBook-Pro-2.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64`) with the Ruby `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]`

```
6.1.0
nc: invalid tcp adaptive write timeout value
Invalid command: echo "hello"
  You appear to be using ssh to clone a git:// URL.
  Make sure your core.gitProxy config option and the
  GIT_PROXY_COMMAND environment variable are NOT set.
```

**Comment by mfazekas** [comment]
@olleolleolle 
I think on MacOS the netcat doesn't understands `-lNU` 
 ` nc: invalid tcp adaptive write timeout value`
 
 Not sure what's the equivalent.

**Comment by kaishuu0123** [comment]
FYI workaround. 
The `use_agent: false` option avoids this issue.
However, the error `can't modify frozen String` isn't suitable

```ruby
Net::SSH.start('host', 'user', password: "password", use_agent: false) do |ssh|
  # snip
end
```
