### ISSUE TITLE
Net::SSH doesn't work when %r is passed to ProxyCommand

### ISSUE THREAD

**Issue by gyfis** [net-ssh/net-ssh#881]
### Expected behavior

We expected the remote user to be picked up correctly when using the `%r` token in the ProxyCommand definition.

### Actual behavior

The command fails with `remote user name not available (ArgumentError)`.

### System configuration

- net-ssh version: 6.1.0
- Ruby version: 3.1.1p18

### Example App

The contents of `~/.ssh/config`

```bash
Host server.myproxy.teleport.sh
    UserKnownHostsFile "/Users/me/.tsh/known_hosts"
    IdentityFile "/Users/me/.tsh/keys/myproxy.teleport.sh/me@example.com"
    CertificateFile "/Users/me/.tsh/keys/myproxy.teleport.sh/me@example.com-ssh/myproxy.teleport.sh-cert.pub"
    PubkeyAcceptedKeyTypes +ssh-rsa-cert-v01@openssh.com
    Port 3022
    ProxyCommand "/usr/local/bin/tsh" proxy ssh --cluster=myproxy.teleport.sh --proxy=myproxy.teleport.sh %r@%h:%p
```

```ruby
gem 'net-ssh', '6.1.0'
require 'net/ssh'

@host = 'server.myproxy.teleport.sh'
@user = 'root'
Net::SSH.start(@host, @user) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```

The error:

```
~/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/proxy/command.rb:53:in `block in open': remote user name not available (ArgumentError)
	from ~/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/proxy/command.rb:42:in `gsub'
	from ~/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/proxy/command.rb:42:in `open'
	from ~/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:70:in `initialize'
	from ~/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `new'
	from ~/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `start'
	from test.rb:6:in `<main>'
```

**Comment by northeastprince** [comment]
This is happening to me too! Using [Teleport](https://goteleport.com).

**Comment by excid3** [comment]
Looks like you need to pass in the `remote_user:` option. 
https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/proxy/command.rb#L48-L52

Maybe that should fallback to `user` if not specified?
