### ISSUE TITLE
connection closed by remote host (bad packet being sent by net-ssh)

### ISSUE THREAD

**Issue by znewsham** [net-ssh/net-ssh#890]
### Expected behavior
Should be able to connect to an SSH host that accepts connections from the ssh command line tool

### Actual behavior
connections created from net-ssh fail after the type 50 packet is sent (debug trace below)

The tech support for the host we are connecting to claims: 
> Your client is trying to make a connection but during the securing part of the SSH tunnel, your side is sending a packet(doing something weird) and that packet is not reassembled on our side.

> Is your library/client RFC Compliant?

Ordinarily we'd assume they were being silly - but the fact that we can connect from the command line and not from net-ssh suggests the problem may be with net-ssh.

```
D, [2023-01-04T17:42:52.231753 #610] DEBUG -- net.ssh.transport.session[258]: establishing connection to safetrans.wellsfargo.com:22
D, [2023-01-04T17:42:52.313043 #610] DEBUG -- net.ssh.transport.session[258]: connection established
I, [2023-01-04T17:42:52.313138 #610]  INFO -- net.ssh.transport.server_version[26c]: negotiating protocol version
D, [2023-01-04T17:42:52.313147 #610] DEBUG -- net.ssh.transport.server_version[26c]: local is `SSH-2.0-Ruby/Net::SSH_7.0.1 x86_64-linux'
D, [2023-01-04T17:42:52.343562 #610] DEBUG -- net.ssh.transport.server_version[26c]: remote is `SSH-2.0-Axway.Gateway'
I, [2023-01-04T17:42:52.343725 #610]  INFO -- net.ssh.transport.algorithms[280]: sending KEXINIT
D, [2023-01-04T17:42:52.343838 #610] DEBUG -- socket[294]: queueing packet nr 0 type 20 len 1436
D, [2023-01-04T17:42:52.343917 #610] DEBUG -- socket[294]: sent 1440 bytes
D, [2023-01-04T17:42:52.371464 #610] DEBUG -- socket[294]: read 280 bytes
D, [2023-01-04T17:42:52.371505 #610] DEBUG -- socket[294]: received packet nr 0 type 20 len 276
I, [2023-01-04T17:42:52.371520 #610]  INFO -- net.ssh.transport.algorithms[280]: got KEXINIT from server
I, [2023-01-04T17:42:52.371541 #610]  INFO -- net.ssh.transport.algorithms[280]: negotiating algorithms
D, [2023-01-04T17:42:52.371578 #610] DEBUG -- net.ssh.transport.algorithms[280]: negotiated:
* kex: ecdh-sha2-nistp256
* host_key: ssh-rsa
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-256
* hmac_server: hmac-sha2-256
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2023-01-04T17:42:52.371584 #610] DEBUG -- net.ssh.transport.algorithms[280]: exchanging keys
D, [2023-01-04T17:42:52.371767 #610] DEBUG -- socket[294]: queueing packet nr 1 type 30 len 76
D, [2023-01-04T17:42:52.371781 #610] DEBUG -- socket[294]: sent 80 bytes
D, [2023-01-04T17:42:52.566079 #610] DEBUG -- socket[294]: read 656 bytes
D, [2023-01-04T17:42:52.566178 #610] DEBUG -- socket[294]: received packet nr 1 type 31 len 636
D, [2023-01-04T17:42:52.566755 #610] DEBUG -- socket[294]: queueing packet nr 2 type 21 len 20
D, [2023-01-04T17:42:52.566834 #610] DEBUG -- socket[294]: sent 24 bytes
D, [2023-01-04T17:42:52.566856 #610] DEBUG -- socket[294]: received packet nr 2 type 21 len 12
D, [2023-01-04T17:42:52.566987 #610] DEBUG -- net.ssh.authentication.session[2a8]: beginning authentication of `any-user'
D, [2023-01-04T17:42:52.567033 #610] DEBUG -- socket[294]: queueing packet nr 3 type 5 len 28
D, [2023-01-04T17:42:52.567041 #610] DEBUG -- socket[294]: sent 64 bytes
D, [2023-01-04T17:42:52.738432 #610] DEBUG -- socket[294]: read 256 bytes
D, [2023-01-04T17:42:52.738583 #610] DEBUG -- socket[294]: received packet nr 3 type 6 len 220
D, [2023-01-04T17:42:52.738637 #610] DEBUG -- net.ssh.authentication.session[2a8]: trying publickey
D, [2023-01-04T17:42:52.738775 #610] DEBUG -- net.ssh.authentication.agent[2bc]: connecting to ssh-agent
E, [2023-01-04T17:42:52.738803 #610] ERROR -- net.ssh.authentication.agent[2bc]: could not connect to ssh-agent: Agent not configured
D, [2023-01-04T17:42:52.738878 #610] DEBUG -- net.ssh.authentication.methods.publickey[2e4]: trying publickey (75:25:16:bc:a9:c1:f9:03:10:12:64:fc:c2:8a:e7:3b)
D, [2023-01-04T17:42:52.738975 #610] DEBUG -- socket[294]: queueing packet nr 4 type 50 len 364
D, [2023-01-04T17:42:52.739050 #610] DEBUG -- socket[294]: sent 400 bytes
D, [2023-01-04T17:42:52.768967 #610] DEBUG -- socket[294]: read 0 bytes
/usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/transport/packet_stream.rb:108:in `block in next_packet': connection closed by remote host (Net::SSH::Disconnect)
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/transport/packet_stream.rb:102:in `loop'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/transport/packet_stream.rb:102:in `next_packet'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/transport/session.rb:190:in `loop'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/transport/session.rb:190:in `poll_message'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/transport/session.rb:175:in `next_message'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/session.rb:102:in `block in next_message'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/session.rb:101:in `loop'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/session.rb:101:in `next_message'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/methods/publickey.rb:52:in `authenticate_with_alg'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/methods/publickey.rb:102:in `block in authenticate_with'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/methods/publickey.rb:99:in `each'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/methods/publickey.rb:99:in `authenticate_with'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/key_manager.rb:131:in `block in each_identity'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/key_manager.rb:128:in `each'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/key_manager.rb:128:in `each_identity'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/session.rb:87:in `block in authenticate'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/session.rb:71:in `each'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh/authentication/session.rb:71:in `authenticate'
	from /usr/local/bundle/gems/net-ssh-7.0.1/lib/net/ssh.rb:254:in `start'
	from test-ssh.rb:53:in `<main>'
```

The "Error" in the middle isn't relevant since the private key is being provided by the `key_data` argument

### System configuration

- net-ssh version 7.0.1
- Ruby version 3.1

### Example App

```
require 'rubygems'
require 'sinatra'
require 'json'
require 'logger'
require 'rack'
require 'base64'

require 'net/ssh'
require 'uri'
require 'stringio'

require 'net/ssh/proxy/http'

# I've tried various options here
options = {
	:port => 22,
	:timeout => 8,
	:non_interactive => true,
	:append_all_supported_algorithms => true,
	:auth_methods => ['publickey'],
	:keys_only => true,
	:key_data => ["<valid private key>"],
	:verbose => Logger::DEBUG,
	:keepalive => true
}

connection = Net::SSH.start("safetrans.wellsfargo.com","any-user", options)
```

**Comment by RemcodM** [comment]
@znewsham You might verify if the connection works if you checkout https://github.com/net-ssh/net-ssh/pull/891 and add option `:pubkey_algorithms => %w[ssh-rsa]`. Not sure if that fixes your particular issue, but it might as well be the solution.

**Comment by znewsham** [comment]
:bow: you are amazing, this did the trick!
