### ISSUE TITLE
Getting error undefined method 'keys' for PASSWORD: string

### ISSUE THREAD

**Issue by noorani786** [net-ssh/net-ssh#906]
### Expected behavior

Tell us what should happen

I am expecting to connect to the SFTP site using .start method

### Actual behavior

Tell us what happens instead.

I am unable to connect to the SFTP site.  Getting the error : 
```
 9: from bin/rails:17:in `<main>'
        8: from bin/rails:17:in `require'
        7: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
        6: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        5: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
        4: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
        3: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
        2: from (irb):2
        1: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:219:in `start'
NoMethodError (undefined method `keys' for "pHUpRLzikof7":String)
```
### System configuration

- net-ssh version : 6.1.0
- Ruby version : 2.5

### Example App

Please provide an example script that reproduces the problem. This will save maintainers time so they can spend it fixing your issues instead of trying to build a reproduction case from sparse instructions.

You can use this as stating point:

```ruby
gem 'net-ssh', '= 6.10'
require 'net/ssh'
puts Net::SSH::Version::CURRENT

@host = 'localhost'
@user = ENV['USER']
Net::SSH.start(@host, @user, @password) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```

Output: 

puts Net::SSH::Version::CURRENT
6.1.0

```
Net::SSH.start(url, username, password)
Traceback (most recent call last):
        9: from bin/rails:17:in `<main>'
        8: from bin/rails:17:in `require'
        7: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
        6: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        5: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
        4: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
        3: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
        2: from (irb):14
        1: from /var/www/ncube_ecomm/shared/bundle/ruby/2.5.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:219:in `start'
NoMethodError (undefined method `keys' for [PASSWORD]:String)
```

**Comment by mfazekas** [comment]
Usage is 

```
Net::SSH.start('host', 'user', password: "password") do |ssh|
```

not 

```
Net::SSH.start('host', 'user',  "password") do |ssh|
```
