### ISSUE TITLE
Connections using hmac-etm gets closed by remote host

### ISSUE THREAD

**Issue by flux-johnm** [net-ssh/net-ssh#910]
### Expected behavior

Connection should be established.

### Actual behavior

After negotiation, the connection gets dropped

```
D, [2023-05-31T12:15:49.481314 #13] DEBUG -- net.ssh.transport.session[53994]: establishing connection to *:22 through proxy
D, [2023-05-31T12:15:49.521082 #13] DEBUG -- net.ssh.transport.session[53994]: connection established
I, [2023-05-31T12:15:49.521173 #13]  INFO -- net.ssh.transport.server_version[539a8]: negotiating protocol version
D, [2023-05-31T12:15:49.521201 #13] DEBUG -- net.ssh.transport.server_version[539a8]: local is `SSH-2.0-Ruby/Net::SSH_7.1.0 x86_64-linux'
D, [2023-05-31T12:15:49.579041 #13] DEBUG -- net.ssh.transport.server_version[539a8]: remote is `SSH-2.0-OpenSSH_6.6'
I, [2023-05-31T12:15:49.579542 #13]  INFO -- net.ssh.transport.algorithms[539bc]: sending KEXINIT
D, [2023-05-31T12:15:49.579703 #13] DEBUG -- socket[539d0]: queueing packet nr 0 type 20 len 1436
D, [2023-05-31T12:15:49.579762 #13] DEBUG -- socket[539d0]: sent 1440 bytes
D, [2023-05-31T12:15:49.581667 #13] DEBUG -- socket[539d0]: read 1344 bytes
D, [2023-05-31T12:15:49.581720 #13] DEBUG -- socket[539d0]: received packet nr 0 type 20 len 1340
I, [2023-05-31T12:15:49.581752 #13]  INFO -- net.ssh.transport.algorithms[539bc]: got KEXINIT from server
I, [2023-05-31T12:15:49.581856 #13]  INFO -- net.ssh.transport.algorithms[539bc]: negotiating algorithms
D, [2023-05-31T12:15:49.581925 #13] DEBUG -- net.ssh.transport.algorithms[539bc]: negotiated:
* kex: diffie-hellman-group14-sha1
* host_key: ssh-rsa
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-512-etm@openssh.com
* hmac_server: hmac-sha2-512-etm@openssh.com
* compression_client: none
* compression_server: none
* language_client:
* language_server:
D, [2023-05-31T12:15:49.581952 #13] DEBUG -- net.ssh.transport.algorithms[539bc]: exchanging keys
D, [2023-05-31T12:15:49.584252 #13] DEBUG -- socket[539d0]: queueing packet nr 1 type 30 len 268
D, [2023-05-31T12:15:49.584297 #13] DEBUG -- socket[539d0]: sent 272 bytes
D, [2023-05-31T12:15:49.616233 #13] DEBUG -- socket[539d0]: read 0 bytes
/bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/packet_stream.rb:108:in `block in next_packet': connection closed by remote host (Net::SSH::Disconnect)
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/packet_stream.rb:102:in `loop'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/packet_stream.rb:102:in `next_packet'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/session.rb:190:in `loop'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/session.rb:190:in `poll_message'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/session.rb:175:in `next_message'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:97:in `send_kexinit'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/kex/abstract.rb:48:in `exchange_keys'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/algorithms.rb:448:in `exchange_keys'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/algorithms.rb:248:in `proceed!'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/algorithms.rb:187:in `accept_kexinit'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/session.rb:190:in `loop'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/session.rb:190:in `poll_message'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/session.rb:227:in `block in wait'
	from /bundle/ruby/3.0.0/bundler/gems/net-ssh-4007b247c157/lib/net/ssh/transport/session.rb:224:in `loop'
```

### System configuration

- local is `SSH-2.0-Ruby/Net::SSH_7.1.0 x86_64-linux'
- remote is `SSH-2.0-OpenSSH_6.6'
- ruby 3.0

**Comment by flux-johnm** [comment]
Is the etm only supported on OpenSSH7 and above?

**Comment by fwininger** [comment]
[OpenSSH 6.2](https://www.openssh.com/txt/release-6.2)/[6.2p1](https://www.openssh.com/txt/release-6.2) (2013-03-22)

Changes since OpenSSH 6.1

* [ssh(1)](https://man.openbsd.org/ssh.1)/[sshd(8)](https://man.openbsd.org/sshd.8): Added support for encrypt-then-mac (EtM) MAC modes
   for SSH protocol 2. These modes alter the packet format and compute
   the MAC over the packet length and encrypted packet rather than over
   the plaintext data. These modes are considered more secure and are
   used by default when available.

**Comment by mfazekas** [comment]
@flux-johnm pls report you os, relevant server config. Also pls check `/var/log/auth.log` for relevant log line for clues on what went wrong. Ideal would be a repro with a VM, so we can also reproduce.

**Comment by ishando** [comment]
I'm getting a similar disconnect though not using hmac-etm
Using publickey method for connections.
Connection from command line works, but when using net-sftp I get:

```
D, [2023-09-06T12:58:17.098806 #171454] DEBUG -- net.ssh.transport.session[5b4]: establishing connection to ****
D, [2023-09-06T12:58:17.170776 #171454] DEBUG -- net.ssh.transport.session[5b4]: connection established
I, [2023-09-06T12:58:17.170838 #171454]  INFO -- net.ssh.transport.server_version[5c8]: negotiating protocol version
D, [2023-09-06T12:58:17.170855 #171454] DEBUG -- net.ssh.transport.server_version[5c8]: local is `SSH-2.0-Ruby/Net::SSH_7.2.0 x86_64-linux'
D, [2023-09-06T12:58:17.220041 #171454] DEBUG -- net.ssh.transport.server_version[5c8]: remote is `SSH-2.0-XFB.Gateway Unix'
I, [2023-09-06T12:58:17.220110 #171454]  INFO -- net.ssh.transport.algorithms[5dc]: sending KEXINIT
D, [2023-09-06T12:58:17.220198 #171454] DEBUG -- socket[5f0]: queueing packet nr 0 type 20 len 420
D, [2023-09-06T12:58:17.220231 #171454] DEBUG -- socket[5f0]: sent 424 bytes
D, [2023-09-06T12:58:17.220417 #171454] DEBUG -- socket[5f0]: read 256 bytes
D, [2023-09-06T12:58:17.220459 #171454] DEBUG -- socket[5f0]: received packet nr 0 type 20 len 252
I, [2023-09-06T12:58:17.220484 #171454]  INFO -- net.ssh.transport.algorithms[5dc]: got KEXINIT from server
I, [2023-09-06T12:58:17.220519 #171454]  INFO -- net.ssh.transport.algorithms[5dc]: negotiating algorithms
D, [2023-09-06T12:58:17.220570 #171454] DEBUG -- net.ssh.transport.algorithms[5dc]: negotiated:
* kex: diffie-hellman-group-exchange-sha1
* host_key: ssh-rsa
* encryption_server: 3des-cbc
* encryption_client: 3des-cbc
* hmac_client: hmac-sha2-256
* hmac_server: hmac-sha2-256
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2023-09-06T12:58:17.220585 #171454] DEBUG -- net.ssh.transport.algorithms[5dc]: exchanging keys
D, [2023-09-06T12:58:17.220644 #171454] DEBUG -- socket[5f0]: queueing packet nr 1 type 34 len 20
D, [2023-09-06T12:58:17.220663 #171454] DEBUG -- socket[5f0]: sent 24 bytes
D, [2023-09-06T12:58:17.345317 #171454] DEBUG -- socket[5f0]: read 152 bytes
D, [2023-09-06T12:58:17.345391 #171454] DEBUG -- socket[5f0]: received packet nr 1 type 31 len 148
D, [2023-09-06T12:58:17.346039 #171454] DEBUG -- socket[5f0]: queueing packet nr 2 type 32 len 140
D, [2023-09-06T12:58:17.346076 #171454] DEBUG -- socket[5f0]: sent 144 bytes
D, [2023-09-06T12:58:17.441291 #171454] DEBUG -- socket[5f0]: read 464 bytes
D, [2023-09-06T12:58:17.441347 #171454] DEBUG -- socket[5f0]: received packet nr 2 type 33 len 444
D, [2023-09-06T12:58:17.442867 #171454] DEBUG -- socket[5f0]: queueing packet nr 3 type 21 len 20
D, [2023-09-06T12:58:17.442891 #171454] DEBUG -- socket[5f0]: sent 24 bytes
D, [2023-09-06T12:58:17.442912 #171454] DEBUG -- socket[5f0]: received packet nr 3 type 21 len 12
D, [2023-09-06T12:58:17.443029 #171454] DEBUG -- net.ssh.authentication.session[604]: beginning authentication of `****'
D, [2023-09-06T12:58:17.443091 #171454] DEBUG -- socket[5f0]: queueing packet nr 4 type 5 len 28
D, [2023-09-06T12:58:17.443109 #171454] DEBUG -- socket[5f0]: sent 64 bytes
D, [2023-09-06T12:58:17.507934 #171454] DEBUG -- socket[5f0]: read 64 bytes
D, [2023-09-06T12:58:17.508064 #171454] DEBUG -- socket[5f0]: received packet nr 4 type 6 len 28
D, [2023-09-06T12:58:17.508132 #171454] DEBUG -- net.ssh.authentication.session[604]: trying publickey
D, [2023-09-06T12:58:17.508320 #171454] DEBUG -- net.ssh.authentication.agent[618]: connecting to ssh-agent
D, [2023-09-06T12:58:17.508402 #171454] DEBUG -- net.ssh.authentication.agent[618]: sending agent request 1 len 44
D, [2023-09-06T12:58:17.508502 #171454] DEBUG -- net.ssh.authentication.agent[618]: received agent packet 5 len 1
D, [2023-09-06T12:58:17.508526 #171454] DEBUG -- net.ssh.authentication.agent[618]: sending agent request 11 len 0
D, [2023-09-06T12:58:17.508565 #171454] DEBUG -- net.ssh.authentication.agent[618]: received agent packet 12 len 5
D, [2023-09-06T12:58:17.508644 #171454] DEBUG -- net.ssh.authentication.methods.publickey[640]: trying publickey (cf:36:d5:fd:0b:e4:fb:e9:03:f3:49:7b:8b:1d:6c:d9) alg rsa-sha2-256
D, [2023-09-06T12:58:17.508766 #171454] DEBUG -- socket[5f0]: queueing packet nr 5 type 50 len 612
D, [2023-09-06T12:58:17.508802 #171454] DEBUG -- socket[5f0]: sent 648 bytes
D, [2023-09-06T12:58:17.548233 #171454] DEBUG -- socket[5f0]: read 600 bytes
D, [2023-09-06T12:58:17.548384 #171454] DEBUG -- socket[5f0]: received packet nr 5 type 60 len 564
D, [2023-09-06T12:58:17.555929 #171454] DEBUG -- socket[5f0]: queueing packet nr 6 type 50 len 1148
D, [2023-09-06T12:58:17.555974 #171454] DEBUG -- socket[5f0]: sent 1184 bytes
D, [2023-09-06T12:58:17.625358 #171454] DEBUG -- socket[5f0]: read 96 bytes
D, [2023-09-06T12:58:17.625454 #171454] DEBUG -- socket[5f0]: received packet nr 6 type 1 len 60
/home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/transport/session.rb:198:in `block in poll_message': disconnected: ssh disconnect host not allowed to connect (1) (Net::SSH::Disconnect)
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/transport/session.rb:190:in `loop'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/transport/session.rb:175:in `next_message'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/session.rb:102:in `block in next_message'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/session.rb:101:in `loop'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/session.rb:101:in `next_message'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:63:in `authenticate_with_alg'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:100:in `block in authenticate_with'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:97:in `each'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:97:in `authenticate_with'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `block in authenticate'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/key_manager.rb:131:in `block in each_identity'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/key_manager.rb:128:in `each'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/key_manager.rb:128:in `each_identity'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:18:in `authenticate'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/session.rb:87:in `block in authenticate'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/session.rb:71:in `each'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/session.rb:71:in `authenticate'
        from /home/ishando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.0/lib/net/ssh.rb:260:in `start'
        from sftp.rb:38:in `ssh_session'
        from sftp.rb:34:in `sftp_client'
        from sftp.rb:29:in `disconnect'
        from sftp.rb:50:in `<main>'
```

All that is shown in /var/log/auth.log is 

```
Sep  6 12:58:16 server ssh-agent[1988]: error: Unknown message 1
```

Using ruby 3.2.2 and net-sftp 4.0.0 on ubuntu 22.04

local is `SSH-2.0-Ruby/Net::SSH_7.2.0 x86_64-linux'
remote is `SSH-2.0-XFB.Gateway Unix'
