### ISSUE TITLE
Connection Failure on FIPS mode when debug mode is enabled.

### ISSUE THREAD

**Issue by Kamori** [net-ssh/net-ssh#936]
### Expected behavior

Expect a ssh connection to provide a complete debug log

### Actual behavior

A connection gets made, but fails during a logging session to print the Pubkey fingerprint

### System configuration

- net-ssh version 7.2.0
- Ruby version 2.7.X

### Failing Version

This collection of code will fail 
```ruby
require 'net/ssh'
DEBUG = true
cmd = "echo 'Hello world'"
@ssh_opts = { config: false,
              timeout: 5,
              use_agent: false,
              fingerprint_hash: "SHA256",
              verbose: DEBUG ? :debug : :fatal }
ssh = Net::SSH.start('example-fips-hosts.com', "MYUSER", @ssh_opts)


...
D, [2024-01-10T12:51:43.453584 #48482] DEBUG -- net.ssh.transport.session[47e0]: establishing connection to example-fips-hosts.com:22
D, [2024-01-10T12:51:48.481952 #48482] DEBUG -- net.ssh.transport.session[47e0]: connection established
I, [2024-01-10T12:51:48.482072 #48482]  INFO -- net.ssh.transport.server_version[47f4]: negotiating protocol version
D, [2024-01-10T12:51:48.482099 #48482] DEBUG -- net.ssh.transport.server_version[47f4]: local is `SSH-2.0-Ruby/Net::SSH_7.2.0 x86_64-linux'
D, [2024-01-10T12:51:48.519444 #48482] DEBUG -- net.ssh.transport.server_version[47f4]: remote is `SSH-2.0-OpenSSH_9.1 PKIX[13.5 FIPS]'
I, [2024-01-10T12:51:48.520094 #48482]  INFO -- net.ssh.transport.algorithms[4808]: sending KEXINIT
D, [2024-01-10T12:51:48.520236 #48482] DEBUG -- socket[481c]: queueing packet nr 0 type 20 len 852
D, [2024-01-10T12:51:48.520282 #48482] DEBUG -- socket[481c]: sent 856 bytes
D, [2024-01-10T12:51:48.542136 #48482] DEBUG -- socket[481c]: read 344 bytes
D, [2024-01-10T12:51:48.542209 #48482] DEBUG -- socket[481c]: received packet nr 0 type 20 len 340
I, [2024-01-10T12:51:48.542239 #48482]  INFO -- net.ssh.transport.algorithms[4808]: got KEXINIT from server
I, [2024-01-10T12:51:48.542286 #48482]  INFO -- net.ssh.transport.algorithms[4808]: negotiating algorithms
D, [2024-01-10T12:51:48.542355 #48482] DEBUG -- net.ssh.transport.algorithms[4808]: negotiated:
* kex: ecdh-sha2-nistp521
* host_key: ecdsa-sha2-nistp256
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-512
* hmac_server: hmac-sha2-512
* compression_client: none
* compression_server: none
* language_client:
* language_server:
D, [2024-01-10T12:51:48.542375 #48482] DEBUG -- net.ssh.transport.algorithms[4808]: exchanging keys
D, [2024-01-10T12:51:48.544001 #48482] DEBUG -- socket[481c]: queueing packet nr 1 type 30 len 148
D, [2024-01-10T12:51:48.544030 #48482] DEBUG -- socket[481c]: sent 152 bytes
D, [2024-01-10T12:51:48.622209 #48482] DEBUG -- socket[481c]: read 376 bytes
D, [2024-01-10T12:51:48.622360 #48482] DEBUG -- socket[481c]: received packet nr 1 type 31 len 356
D, [2024-01-10T12:51:48.623564 #48482] DEBUG -- socket[481c]: queueing packet nr 2 type 21 len 20
D, [2024-01-10T12:51:48.623620 #48482] DEBUG -- socket[481c]: sent 24 bytes
D, [2024-01-10T12:51:48.623670 #48482] DEBUG -- socket[481c]: received packet nr 2 type 21 len 12
D, [2024-01-10T12:51:48.623923 #48482] DEBUG -- net.ssh.authentication.session[4830]: beginning authentication of `MYUSER'
D, [2024-01-10T12:51:48.624020 #48482] DEBUG -- socket[481c]: queueing packet nr 3 type 5 len 28
D, [2024-01-10T12:51:48.624044 #48482] DEBUG -- socket[481c]: sent 96 bytes
D, [2024-01-10T12:51:48.709962 #48482] DEBUG -- socket[481c]: read 96 bytes
D, [2024-01-10T12:51:48.710159 #48482] DEBUG -- socket[481c]: received packet nr 3 type 6 len 28
D, [2024-01-10T12:51:48.710260 #48482] DEBUG -- net.ssh.authentication.session[4830]: trying none
D, [2024-01-10T12:51:48.710383 #48482] DEBUG -- socket[481c]: queueing packet nr 4 type 50 len 44
D, [2024-01-10T12:51:48.710424 #48482] DEBUG -- socket[481c]: sent 112 bytes
D, [2024-01-10T12:51:48.740794 #48482] DEBUG -- socket[481c]: read 96 bytes
D, [2024-01-10T12:51:48.740980 #48482] DEBUG -- socket[481c]: received packet nr 4 type 51 len 28
D, [2024-01-10T12:51:48.741047 #48482] DEBUG -- net.ssh.authentication.session[4830]: allowed methods: publickey
D, [2024-01-10T12:51:48.741098 #48482] DEBUG -- net.ssh.authentication.methods.none[4844]: none failed
D, [2024-01-10T12:51:48.741135 #48482] DEBUG -- net.ssh.authentication.session[4830]: trying publickey
Traceback (most recent call last):
	... 25 levels...
	16: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/key_manager.rb:128:in `each'
	15: from /my/hostvendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/key_manager.rb:131:in `block in each_identity'
	14: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `block in authenticate'
	13: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:97:in `authenticate_with'
	12: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:97:in `each'
	11: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:100:in `block in authenticate_with'
	10: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:47:in `authenticate_with_alg'
	 9: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/loggable.rb:25:in `debug'
	 8: from /opt/rubies/ruby-2.7/lib/ruby/2.7.0/logger.rb:468:in `add'
	 7: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/loggable.rb:25:in `block in debug'
	 6: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/methods/publickey.rb:47:in `block in authenticate_with_alg'
	 5: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/pub_key_fingerprint.rb:27:in `fingerprint'
	 4: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/pub_key_fingerprint.rb:33:in `fingerprint'
	 3: from /my/host/vendor/bundle/ruby/2.7.0/gems/net-ssh-7.2.0/lib/net/ssh/authentication/pub_key_fingerprint.rb:33:in `hexdigest'
	 2: from /opt/rubies/ruby-2.7/lib/ruby/2.7.0/openssl/digest.rb:35:in `digest'
	 1: from /opt/rubies/ruby-2.7/lib/ruby/2.7.0/openssl/digest.rb:35:in `digest'
/opt/rubies/ruby-2.7/lib/ruby/2.7.0/openssl/digest.rb:35:in `initialize': Digest initialization failed: disabled for FIPS (OpenSSL::Digest::DigestError)
```

However, if I run the following with DEBUG off, I get my expected outcome.

```ruby
require 'net/ssh'
DEBUG = false
cmd = "echo 'Hello world'"
@ssh_opts = { config: false,
              timeout: 5,
              use_agent: false,
              fingerprint_hash: "SHA256",
              verbose: DEBUG ? :debug : :fatal }
ssh = Net::SSH.start('example-fips-hosts.com', "MYUSER", @ssh_opts)

...
Valid connection
```

**Comment by mfazekas** [comment]
@Kamori thanks for the report

I think the issue needs to be addressed here. The simplest fix probably adding 

```ruby
algorithm = 'SHA256' if algorithm = 'MD5' && OpenSSL.fips_mode
```

https://github.com/net-ssh/net-ssh/blob/f54a2270dba3974081663b9780b493ed8d332a07/lib/net/ssh/authentication/pub_key_fingerprint.rb#L30-L39
