### ISSUE TITLE
Unable to establish SSH connection due to key exchange algorithm mismatch

### ISSUE THREAD

**Issue by ahasunos** [net-ssh/net-ssh#940]
### Expected behavior
The script should establish an SSH connection to the specified host and execute the provided command successfully, printing the output.

### Actual behavior

The script fails to establish an SSH connection and raises an error related to key exchange algorithm negotiation.
```
Net::SSH::Exception: could not settle on kex algorithm
Server kex preferences: curve25519-sha256@libssh.org,kex-strict-s-v00@openssh.com
Client kex preferences: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1

```

### Additional Info
The target server (an ubuntu ec2 instance in my case) is hardened to only support the curve25519 for key exchange. I am able to ssh to the machine using `ssh -i private-key.pem username@hostname`

### System configuration

- net-ssh version: 7.2.1
- Ruby version: 3.1.0

### Example App

Use the below example script that reproduces the problem.

```ruby
require 'net/ssh'

hostname = "example.com" # Replace with actual hostname or IP address
username = "username"    # Replace with actual username
opts = {
  :user_known_hosts_file => "/dev/null",
  :port => 22,
  :compression => false,
  :compression_level => 0,
  :keepalive => true,
  :keepalive_interval => 60,
  :timeout => 15,
  :auth_methods => ["none", "publickey"],
  :keys_only => true,
  :keys => ["/path/to/your/ssh/key.pem"], # Replace with actual path to SSH private key
  :forward_agent => false,
  :non_interactive => false,
  :append_all_supported_algorithms => true,
  :config => true,
  :verify_host_key => :never
}

ssh = Net::SSH.start(hostname, username, opts)
output = ssh.exec!("pwd")
puts output
ssh.close

```

### Stacktrace
```
/Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/algorithms.rb:415:in `negotiate': could not settle on kex algorithm (Net::SSH::Exception)
Server kex preferences: curve25519-sha256@libssh.org,kex-strict-s-v00@openssh.com
Client kex preferences: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/algorithms.rb:388:in `negotiate_algorithms'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/algorithms.rb:252:in `proceed!'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/algorithms.rb:192:in `accept_kexinit'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:190:in `loop'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:190:in `poll_message'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:227:in `block in wait'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:224:in `loop'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:224:in `wait'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:89:in `initialize'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh.rb:258:in `new'
        from /Users/*******/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh.rb:258:in `start'
        from test.rb:6:in `<main>'
```

**Comment by ahasunos** [comment]
Closing this issue as I found the fix in the readme, should have gone thoroughly:
https://github.com/net-ssh/net-ssh?tab=readme-ov-file#install `For curve25519-sha256 kex exchange support your bundle file should contain x25519 dependency.`
