### ISSUE TITLE
Failing tests of old unsupported ciphers on Fedora

### ISSUE THREAD

**Issue by voxik** [net-ssh/net-ssh#952]
On Fedora, we observe a lot of test failures due crypto settings, which tries to set high bar for security and disables the old ciphers. E.g.:

~~~
  1) Error:
Transport::TestCipherFactory#test_lengths_for_blowfish_cbc:
OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (BF-CBC : 13), Properties ())
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `initialize'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `new'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `get_lengths'
    transport/test_cipher_factory.rb:18:in `test_lengths_for_blowfish_cbc'
  2) Error:
Transport::TestCipherFactory#test_lengths_for_cast128_ctr:
OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (CAST5-ECB : 0), Properties ())
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `initialize'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `new'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `get_lengths'
    transport/test_cipher_factory.rb:72:in `test_lengths_for_cast128_ctr'
  3) Error:
Transport::TestCipherFactory#test_cast128_ctr_for_decryption:
OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (CAST5-ECB : 0), Properties ())
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `initialize'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `new'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `get'
    transport/test_cipher_factory.rb:290:in `decrypt'
    transport/test_cipher_factory.rb:174:in `test_cast128_ctr_for_decryption'
  4) Error:
Transport::TestCipherFactory#test_blowfish_cbc_for_encryption:
OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (BF-CBC : 13), Properties ())
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `initialize'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `new'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `get'
    transport/test_cipher_factory.rb:265:in `encrypt'
    transport/test_cipher_factory.rb:78:in `test_blowfish_cbc_for_encryption'
  5) Error:
Transport::TestCipherFactory#test_lengths_for_cast128_cbc:
OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (CAST5-CBC : 35), Properties ())
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `initialize'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `new'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `get_lengths'
    transport/test_cipher_factory.rb:32:in `test_lengths_for_cast128_cbc'
  6) Error:
Transport::TestCipherFactory#test_idea_cbc_for_encryption:
OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (IDEA-CBC : 31), Properties ())
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `initialize'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `new'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `get'
    transport/test_cipher_factory.rb:265:in `encrypt'
    transport/test_cipher_factory.rb:89:in `test_idea_cbc_for_encryption'
  7) Error:
Transport::TestCipherFactory#test_cast128_cbc_for_decryption:
OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (CAST5-CBC : 35), Properties ())
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `initialize'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `new'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `get'
    transport/test_cipher_factory.rb:290:in `decrypt'
    transport/test_cipher_factory.rb:114:in `test_cast128_cbc_for_decryption'
  8) Error:
Transport::TestCipherFactory#test_blowfish_ctr_for_encryption:
OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (BF-ECB : 0), Properties ())
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `initialize'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `new'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:50:in `get'
    transport/test_cipher_factory.rb:265:in `encrypt'
    transport/test_cipher_factory.rb:160:in `test_blowfish_ctr_for_encryption'
  9) Error:
Transport::TestCipherFactory#test_lengths_for_blowfish_ctr:
OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (BF-ECB : 0), Properties ())
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `initialize'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `new'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `get_lengths'
    transport/test_cipher_factory.rb:68:in `test_lengths_for_blowfish_ctr'
 10) Error:
Transport::TestCipherFactory#test_lengths_for_idea_cbc:
OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (IDEA-CBC : 31), Properties ())
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `initialize'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `new'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `get_lengths'
    transport/test_cipher_factory.rb:23:in `test_lengths_for_idea_cbc'

... snip ...

461) Error:
Authentication::TestKeyManager#test_sign_with_agent_originated_key_should_be_signable_through_explicitly_loaded_cert:
OpenSSL::PKey::PKeyError: EVP_DigestSignInit: invalid digest
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/openssl.rb:121:in `sign'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/openssl.rb:121:in `ssh_do_sign'
    /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/authentication/certificate.rb:92:in `sign!'
    authentication/test_key_manager.rb:319:in `rsa_cert'
    authentication/test_key_manager.rb:217:in `test_sign_with_agent_originated_key_should_be_signable_through_explicitly_loaded_cert'
1574 runs, 4356 assertions, 150 failures, 311 errors, 0 skips
RPM build errors:
~~~

And I wonder if there is chance to somehow clean this up, because it is not easy to spot the real errors.

Sorry for a such broad ticket, but I am not expert in crypto and not sure where to start.

**Comment by voxik** [comment]
E.g. to this error:

> ~~~
>   1) Error:
> Transport::TestCipherFactory#test_lengths_for_blowfish_cbc:
> OpenSSL::Cipher::CipherError: unsupported (Global default library context, Algorithm (BF-CBC : 13), Properties ())
>     /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `initialize'
>     /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `new'
>     /builddir/build/BUILD/rubygem-net-ssh-7.1.0-build/net-ssh-7.1.0/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/transport/cipher_factory.rb:83:in `get_lengths'
>     transport/test_cipher_factory.rb:18:in `test_lengths_for_blowfish_cbc'
> ~~~

I was provided [this](https://bugzilla.redhat.com/show_bug.cgi?id=2311882#c1) explanation:

_the first test failure attempts to use the Blowfish-CBC cipher. Blowfish hasn't been available except from the legacy provider since OpenSSL 3.0: https://github.com/openssl/openssl/commit/f5056577ba08b3694aab2722eae1c97bf00acc80. Unless you made changes to enable the legacy provider, this test should have failed ever since OpenSSL 3.0._

**Comment by voxik** [comment]
BTW the full set of errors currently on Fedora can be obtained by cliking on `build.log` [here](https://koschei.fedoraproject.org/package/rubygem-net-ssh)
